import { useId } from "react";
import type { SVGProps } from "react";

/**
 * The app icon – GENERATED by scripts/gen-from-app.mjs from
 * public/brand/gloumi-mark.svg (the app's Gloumi-icon-light-default.svg).
 *
 * A "G" cut out of a square, revealing the four tab colours behind it. The
 * mask id is unique per instance so two marks on a page do not share one.
 */
const G_PATHS: readonly string[] = [
  "M551.472,266.944C583.313,271.204 583.391,270.631 614.43,278.74C616.161,279.192 657.709,292.222 683.112,312.993C765.112,380.04 661.277,460.318 638.586,389.473C619.893,331.112 618.332,288.638 548.557,275.195C499.004,265.648 372.79,289.389 380.134,528.511C385.309,697.017 474.558,758.359 543.355,737.012C559.399,732.034 576.969,715.374 570.048,688.603C558.607,644.349 527.42,611.721 554.762,583.778C566.729,571.547 608.016,571.987 623.625,629.462C634.071,667.925 608.176,760.911 477.54,748.18C380.87,738.759 334.756,685.29 321.338,669.639C257.685,595.394 229.589,447.216 335.702,336.693C379.117,291.473 458.287,261.27 540.511,266.311C546.027,266.649 546.008,266.699 546.486,266.727C549.08,266.877 548.981,266.8 551.472,266.944Z",
  "M641.061,637.529C640.029,630.691 637.876,600.147 616.906,572.189C581.742,525.306 531.532,519.783 518.441,517.837C511.265,516.77 514.599,511.108 517.523,510.656C522.18,509.937 623.303,510.101 632.501,510.116C740.247,510.29 741.231,509.914 742.558,512.463C746.056,519.179 732.417,517.877 722.761,523.894C713.033,529.954 714.448,532.776 714.454,644.5C714.458,738.197 714.937,739.179 712.436,740.386C709.026,742.032 646.598,740.917 645.45,740.831C637.936,740.267 644.841,706.534 641.061,637.529Z",
  "M762.557,680.968C778.511,680.764 788.289,683.47 795.843,700.347C805.713,722.4 785.888,738.044 775.582,740.795C734.71,751.706 718.842,691.255 762.557,680.968Z"
];

const G_TRANSFORM = "matrix(1.224609,0,0,1.224609,0,0)";

const CIRCLES = [
  {
    "cx": 350,
    "cy": 300,
    "r": 380,
    "fill": "#574463"
  },
  {
    "cx": 900,
    "cy": 860,
    "r": 420,
    "fill": "#4C6552"
  },
  {
    "cx": 860,
    "cy": 260,
    "r": 290,
    "fill": "#8F3D26"
  }
] as const;

type BrandMarkProps = Omit<SVGProps<SVGSVGElement>, "viewBox" | "role"> & {
  title?: string;
  /** Square behind the mark; `null` leaves it transparent. */
  background?: string | null;
};

export function BrandMark({ title = "Gloumi", background = "#FFFFFF", className, ...rest }: BrandMarkProps) {
  const maskId = `gloumi-mark-${useId().replace(/[^a-zA-Z0-9_-]/g, "")}`;
  const decorative = title === "";
  return (
    <svg
      viewBox="84 74 1100 1100"
      role={decorative ? undefined : "img"}
      aria-hidden={decorative ? true : undefined}
      aria-label={decorative ? undefined : title}
      focusable="false"
      className={className}
      {...rest}
    >
      <defs>
        <mask id={maskId} maskUnits="userSpaceOnUse" x="84" y="74" width="1100" height="1100">
          <rect x="84" y="74" width="1100" height="1100" fill="#FFFFFF" />
          <g fill="#000000" transform={G_TRANSFORM}>
            {G_PATHS.map((d, i) => (
              <path key={i} d={d} />
            ))}
          </g>
        </mask>
      </defs>
      {background ? <rect x="84" y="74" width="1100" height="1100" fill={background} /> : null}
      <g mask={`url(#${maskId})`}>
        <rect x="84" y="74" width="1100" height="1100" fill="#7A3350" />
        {CIRCLES.map((c) => (
          <circle key={c.fill} cx={c.cx} cy={c.cy} r={c.r} fill={c.fill} />
        ))}
      </g>
    </svg>
  );
}
