// GENERATED by scripts/gen-faq.mjs from the support role's FAQ draft
// (Gloumi office pagalba/DUK.md). Do not edit by hand: change the draft or
// the script's HOLD list, then regenerate.
//
// Published now: what holds under Terms 1.12 (Gloumi #209). Held back: K-9, K-28, K-40, K-43, K-54.
// Answers may refer to another item as "K-n"; the page turns that into a link.
import type { Lang } from "./lang";

export type FaqItem = { id: string; q: string; a: string };
export type FaqSection = { key: string; title: string; items: FaqItem[] };

export const FAQ_UPDATED = "2026-10-05";

export const FAQ: Record<Lang, FaqSection[]> = {
  "lt": [
    {
      "key": "about",
      "title": "Apie Gloumi",
      "items": [
        {
          "id": "K-1",
          "q": "Kas yra Gloumi?",
          "a": "Programėlė, kurioje randate grožio meistrus, matote jų darbus, kainas ir laisvą laiką ir iš karto rezervuojate vizitą. Paslaugas teikia meistrai savo vardu, o Gloumi atsako už programėlę ir mokėjimus joje."
        },
        {
          "id": "K-2",
          "q": "Ar Gloumi nemokama?",
          "a": "Klientams – taip: mokate tik meistro nustatytą kainą, Gloumi nieko neprideda. Meistrams Starter kainuoja 0 € per mėn., o Gloumi ima komisinį; Pro ir VIP Studio – mokami planai."
        },
        {
          "id": "K-3",
          "q": "Kaip susisiekti su pagalba?",
          "a": "Šoninis meniu → Pagalba → Neradote atsakymo? arba info@gloumi.lt. Dėl konkretaus vizito – jame „Pranešti apie problemą“. Gavimą patvirtiname per 2 darbo dienas, atsakome per 14 d., dažniausiai greičiau."
        }
      ]
    },
    {
      "key": "account",
      "title": "Paskyra",
      "items": [
        {
          "id": "K-4",
          "q": "Kaip užsiregistruoti ir prisijungti?",
          "a": "Prisijungimo lange – „Registruokitės“: penki žingsniai ir el. pašto patvirtinimas. Galima per Google, iPhone – ir per Apple. Prisijungiama el. paštu ar vartotojo vardu su slaptažodžiu arba per Google ar Apple. Nuo 14 metų."
        },
        {
          "id": "K-5",
          "q": "Pamiršau slaptažodį.",
          "a": "Prisijungimo lange – „Pamiršau slaptažodį“: įveskite el. paštą ir paspauskite nuorodą laiške. Laiško ieškokite ir šlamšte. Registravotės per Google ar Apple? Prisijunkite tuo pačiu mygtuku."
        },
        {
          "id": "K-6",
          "q": "Neatėjo el. pašto patvirtinimo laiškas.",
          "a": "Patikrinkite šlamšto aplanką. Naują nuorodą išsisiųsite: šoninis meniu → Programos nustatymai → Paskyra → Patvirtinti prie el. pašto."
        },
        {
          "id": "K-7",
          "q": "Kaip pakeisti savo duomenis?",
          "a": "Vardą ir aprašymą – Profilis → Redaguoti profilį, nuotrauką – ją paspaudę. El. paštą, vartotojo vardą ir telefoną – šoninis meniu → Programos nustatymai → Paskyra. Gimimo datą pakeisime mes – parašykite."
        },
        {
          "id": "K-8",
          "q": "Kaip pakeisti kalbą ar temą?",
          "a": "Šoninis meniu → Programos nustatymai → Kalba / Language (lietuvių ar anglų) arba „Programėlės tema“. Pakeitimas įsigalioja iš karto."
        },
        {
          "id": "K-10",
          "q": "Kaip gauti savo duomenų kopiją?",
          "a": "Šoninis meniu → Programos nustatymai → Paskyra → Atsisiųsti mano duomenis – JSON failas be nuotraukų ir balso įrašų. Visų duomenų prašykite info@gloumi.lt iš paskyros el. pašto – atsakysime per mėnesį."
        },
        {
          "id": "K-11",
          "q": "Kažkas prisijungė prie mano paskyros.",
          "a": "Šoninis meniu → Programos nustatymai → Paskyra → Atsijungti visur, tada prisijungimo lange – „Pamiršau slaptažodį“. Parašykite mums, ko nedarėte. Gloumi niekada neprašo slaptažodžio ar kodo."
        }
      ]
    },
    {
      "key": "visits",
      "title": "Vizitai",
      "items": [
        {
          "id": "K-12",
          "q": "Kaip rasti meistrą?",
          "a": "„Paieška“: ieškokite pagal paslaugą, meistrą ar saloną, naudokite „Filtrai“ ar „Žemėlapis“. „Atrasti“ – meistrų darbų srautas."
        },
        {
          "id": "K-13",
          "q": "Kaip rezervuoti vizitą?",
          "a": "Meistro profilyje – „Rezervuoti laiką“: pasirinkite paslaugas, datą ir laiką, mokėjimo būdą ir paspauskite „Patvirtinti rezervaciją“. Kai meistras patvirtins, gausite pranešimą."
        },
        {
          "id": "K-14",
          "q": "Kada vizitas tikrai rezervuotas?",
          "a": "Kai meistras jį patvirtina: „Laukia patvirtinimo“ pasikeičia į „Patvirtintas“. Iki tol atšaukti galite bet kada, ir sumokėta suma grąžinama visa. Tas pats, jei meistras atmeta."
        },
        {
          "id": "K-15",
          "q": "Visi laikai užimti – ar galiu laukti eilėje?",
          "a": "Taip. Pasirinkę užimtą dieną paspauskite „Prisijungti prie eilės“. Kai kas nors tą dieną atšauks vizitą, pirmas eilėje gaus pranešimą ir galės rezervuoti tą laiką."
        },
        {
          "id": "K-16",
          "q": "Ką rašyti vizito pastabose?",
          "a": "Tai, ką meistrui verta žinoti iš anksto: ankstesnes formules, spalvas, pageidavimus. Galite pridėti nuotrauką („Pridėti viziją“). Apie alergijas ar jautrumą pasakykite meistrui tiesiogiai."
        },
        {
          "id": "K-17",
          "q": "Kaip atšaukti ar perkelti vizitą?",
          "a": "Užsakymai → Atšaukti rezervaciją arba Perkelti. Atšaukiama iš karto, neklausiant. Likus mažiau nei 24 val. iki patvirtinto vizito perkelti gali tik meistras – parašykite jam."
        },
        {
          "id": "K-18",
          "q": "Ar atgausiu pinigus, jei atšauksiu?",
          "a": "Atšaukus likus daugiau nei 24 val. arba meistrui atšaukus – grąžinama visa programėlėje sumokėta suma. Atšaukus patvirtintą vizitą vėliau ar neatvykus, avansas gali likti meistrui pagal jo atšaukimo sąlygas, likusi suma grąžinama."
        },
        {
          "id": "K-19",
          "q": "Kada grįš grąžinti pinigai?",
          "a": "Grąžinimą pradedame iš karto, pinigai grįžta tuo pačiu būdu, kuriuo mokėjote. Kada jie pasirodys sąskaitoje, priklauso nuo banko. Ilgai nematote – parašykite mums."
        },
        {
          "id": "K-20",
          "q": "Meistras neatvyko arba vizitas neįvyko.",
          "a": "Mokėjote programėlėje? Atidarykite vizitą ir paspauskite „Vizitas neįvyko?“ – iki 72 val. po vizito pabaigos. Išmoka meistrui sulaikoma, sprendimą priima žmogus. Vėliau ar mokėjus vietoje – rašykite mums."
        },
        {
          "id": "K-21",
          "q": "Paslauga nepatiko.",
          "a": "Pirmiausia parašykite meistrui – paslaugą teikia jis. Mes padedame surinkti faktus ir sprendžiame dėl mokėjimo programėlėje. Nesusitarus nemokamai kreiptis galite į Valstybinę vartotojų teisių apsaugos tarnybą (vvtat.lt)."
        },
        {
          "id": "K-22",
          "q": "Kaip palikti atsiliepimą?",
          "a": "Kai meistras pažymi vizitą atliktu: Užsakymai → Atliktos procedūros → Įvertinti meistrą. Galima per 48 val. po vizito ir tik po įvykusio vizito. Paskelbto pakeisti negalite – parašykite mums."
        }
      ]
    },
    {
      "key": "payments",
      "title": "Mokėjimai",
      "items": [
        {
          "id": "K-23",
          "q": "Kaip apmokamas vizitas?",
          "a": "Kokius mokėjimo būdus priimti, renkasi meistras: „Grynieji“, „Kortele salone“ ar „Programėlėje“. Programėlėje mokama kortele ar Apple Pay, kvitą Stripe atsiunčia el. paštu. Per 30 min. neapmokėtas vizitas atšaukiamas."
        },
        {
          "id": "K-24",
          "q": "Ar saugu mokėti programėlėje?",
          "a": "Mokėjimus vykdo Stripe – Gloumi kortelės duomenų nemato ir nesaugo. Kortelės numerio, kodų ar slaptažodžių laišku ar žinute niekada neprašome."
        },
        {
          "id": "K-25",
          "q": "Kas yra avansas?",
          "a": "Dalis kainos – suma ar procentas, – kurią meistras prašo sumokėti programėlėje rezervuojant. Avansas įskaitomas į kainą, likusią sumą mokate vietoje. Kada grąžinamas – K-18."
        },
        {
          "id": "K-26",
          "q": "Kaip palikti arbatpinigių?",
          "a": "Po atsiliepimo su 3 ar daugiau žvaigždučių, jei meistras juos priima: 5, 10, 15 % ar 1–100 €, per 7 d. po vizito. Vėliau – Užsakymai → Atliktos procedūros → Palikti arbatpinigių. Gloumi iš jų nieko neima."
        },
        {
          "id": "K-27",
          "q": "Kaip veikia dovanų kortelės?",
          "a": "Šoninis meniu → Dovanų kortelė: pirkite (40–1000 €) arba „Turiu kodą“ – panaudokite. Suma virsta kreditu, kurį pritaikote mokėdami programėlėje. Nepanaudotą kortelę atšaukti galima per 14 d. – parašykite mums."
        },
        {
          "id": "K-29",
          "q": "Meistras davė savo kodą – ką su juo daryti?",
          "a": "Rezervuodami paspauskite „Turiu meistro kodą“, įveskite kodą ir „Pritaikyti“ arba atidarykite meistro nuorodą. Kaina nuo kodo nesikeičia."
        },
        {
          "id": "K-30",
          "q": "Bankas rodo dvi vienodas sumas.",
          "a": "Dažnai tai laikinas sumos sulaikymas banke – jis dingsta per kelias dienas. Jei nuskaityta dukart, parašykite mums, kada ir kiek mokėjote. Kortelės numerio nesiųskite."
        }
      ]
    },
    {
      "key": "masters",
      "title": "Meistrams",
      "items": [
        {
          "id": "K-31",
          "q": "Kaip tapti meistru?",
          "a": "Profilis → Tapti meistru: nuotrauka, vardas ir miestas, aprašymas, sritis ir sutikimas su sąlygomis. Meistru gali tapti asmuo nuo 18 metų. Kliento ir meistro režimą perjungsite profilio viršuje."
        },
        {
          "id": "K-32",
          "q": "Ką užpildyti, kad klientai galėtų rezervuoti?",
          "a": "Paspauskite „Pridėti paslaugas“ ir pereikite vedlį iki „Aktyvuoti profilį“. Reikia paslaugų, darbo laiko, sričių ir (jei dirbate savo vietoje) adreso; „Priima rezervacijas“ turi būti įjungta."
        },
        {
          "id": "K-33",
          "q": "Kaip pridėti ar pakeisti paslaugas?",
          "a": "Profilis → Paslaugos ir laikas → Paslaugos ir kainos → Nauja paslauga. Avansas – Profilis → Verslas → Mokėjimai → Prašyti avanso. Per „Kokias paslaugas teikiate?“ nekeiskite – pakeičiamas visas kainoraštis."
        },
        {
          "id": "K-34",
          "q": "Kaip nustatyti darbo laiką ir poilsio dienas?",
          "a": "Profilis → Paslaugos ir laikas → Darbo laikas → Savaitės grafikas. Atskirą dieną ar atostogas pažymėkite paspaudę datą kalendoriuje („Poilsio diena“). Laikinai – išjunkite „Priima rezervacijas“."
        },
        {
          "id": "K-35",
          "q": "Kaip užblokuoti laiką ar įrašyti klientą pačiam?",
          "a": "Kalendorius → Užblokuoti laiką – vienai dienai ar kas savaitę (pertrauka). „Pridėti vizitą“ – savo klientui: vizitas iškart patvirtintas, be avanso, klientas gauna pranešimą."
        },
        {
          "id": "K-36",
          "q": "Kaip patvirtinti, atmesti, atšaukti ar perkelti vizitą?",
          "a": "Kalendorius → Prašymai → Patvirtinti arba „Atmesti“ – atsakykite greitai. Atšaukti ar perkelti – atidarius vizitą. Atšaukus klientui grąžinama visa suma; perkelti – tik suderinus su klientu."
        },
        {
          "id": "K-37",
          "q": "Kaip pažymėti vizitą atliktu?",
          "a": "Atidarykite vizitą → Užbaigti vizitą (nuo vizito pradžios). Po vizito atsakykite „Ar klientas atvyko?“ – kitaip po 24 val. jis pasižymės įvykęs. Atsiliepimą klientas palieka tik po atlikto vizito."
        },
        {
          "id": "K-38",
          "q": "Kaip priimti mokėjimus programėlėje?",
          "a": "Profilis → Verslas → Mokėjimai → Stripe mokėjimų nustatymai → Įjungti mokėjimus internetu; tapatybę patvirtinsite Stripe lange. Neužbaigus per 30 d. nuo kliento mokėjimo, pinigai grąžinami klientui."
        },
        {
          "id": "K-39",
          "q": "Kada gaunu pinigus?",
          "a": "Ne anksčiau kaip po 72 val. nuo vizito pabaigos, paprastai per 7 d., jei klientas nepranešė, kad vizitas neįvyko. Į banką – pagal Stripe išmokų tvarkaraštį. Išmokas matote Profilis → Verslas → Mokėjimai."
        },
        {
          "id": "K-41",
          "q": "Kas yra meistro kodas?",
          "a": "Profilis → Verslas → Mokėjimai → Kodas jūsų klientams. Duokite jį klientams iš laikų iki Gloumi – už juos komisinio neimame. Iki 50 klientų, galioja 3 mėn. Per Gloumi jus radusiems duoti negalima."
        },
        {
          "id": "K-42",
          "q": "Kodėl prašoma asmens ar įmonės kodo ir IBAN?",
          "a": "To reikalauja ES taisyklė DAC7: apie per platformą uždirbtas pajamas pranešama VMI. Įveskite juos šoniniame meniu → Programos nustatymai → Veiklos duomenys. Klientai jų nemato. Nepateikus per 60 d., išmokos sulaikomos."
        },
        {
          "id": "K-44",
          "q": "Kaip atšaukti prenumeratą ar susigrąžinti pinigus?",
          "a": "Parduotuvėje: iPhone – Nustatymai → jūsų vardas → Prenumeratos; Android – Google Play → Mokėjimai ir prenumeratos → Prenumeratos. App Store – ne vėliau kaip likus 24 val. iki laikotarpio pabaigos. Grąžinimus sprendžia Apple ar Google. Ištrynus paskyrą prenumerata nesibaigia."
        },
        {
          "id": "K-45",
          "q": "Kaip sukurti saloną?",
          "a": "Profilis → Verslas → Salonas → Sukurti saloną (reikia VIP Studio). Pakvieskite iki 10 meistrų pagal vartotojo vardą. Nariai lieka savarankiški ir gauna Pro funkcijas, o jūs matote jų vizitus."
        },
        {
          "id": "K-46",
          "q": "Ar galima pašalinti atsiliepimą?",
          "a": "Tikrų neigiamų atsiliepimų nešaliname – tik pažeidžiančius taisykles, melagingus ar nesusijusius su paslauga; tokį nurodykite info@gloumi.lt."
        },
        {
          "id": "K-47",
          "q": "Klientas pranešė, kad vizitas neįvyko.",
          "a": "Išmoka už vizitą sulaikoma, kol išsiaiškinsime. Matote kliento žinutę – paaiškinkite ir, jei paprašysime, atsiųskite įrodymų. Sprendimą priima žmogus, apie jį pranešame programėlėje ir el. paštu."
        },
        {
          "id": "K-48",
          "q": "Mano paskyra apribota.",
          "a": "Pranešime nurodome priežastį ir taisyklę. Paaiškinti ar apskųsti galite nemokamai – per „Pagalba“ arba info@gloumi.lt. Skundą nagrinėja žmogus, atsakome raštu; nepagrįstą apribojimą panaikiname iš karto."
        },
        {
          "id": "K-49",
          "q": "Ar galiu įvertinti klientą?",
          "a": "Taip – užbaigus vizitą programėlė pasiūlys „Įvertinkite klientą“. Įvertinimą mato kiti meistrai, tekstą – tik jie. Vertinkite sąžiningai ir tik pagal tą vizitą."
        }
      ]
    },
    {
      "key": "content",
      "title": "Turinys, pranešimai ir saugumas",
      "items": [
        {
          "id": "K-50",
          "q": "Kaip įkelti Story ar darbo nuotrauką?",
          "a": "Sraute pasirinkite naują Story ar įrašą. Tik iCloud esantį video pirma atsisiųskite į telefoną. Failas – iki 60 MB, Story video – iki 1 min."
        },
        {
          "id": "K-51",
          "q": "Kaip pranešti apie netinkamą turinį ar žmogų?",
          "a": "Žinutę palaikykite nuspaudę → Pranešti; meistro profilyje – ženklas viršuje. Pasirinkite priežastį → Išsiųsti pranešimą. Pranešimas anonimiškas, jį peržiūri mūsų komanda. Kam nors gresia pavojus – skambinkite 112."
        },
        {
          "id": "K-52",
          "q": "Kaip užblokuoti žmogų?",
          "a": "Pranešimo lange – „Blokuoti vartotoją“: nebematysite jo įrašų, Story ir žinučių. Atblokuoti – šoninis meniu → Programos nustatymai → Užblokuoti žmonės."
        },
        {
          "id": "K-53",
          "q": "Kaip tvarkyti pranešimus? Kodėl jie neateina?",
          "a": "Varpelis viršuje: braukite kairėn – ištrinti, „Tvarkyti“ – keli iš karto. Neateina? Telefono nustatymuose leiskite Gloumi pranešimus ir būkite prisijungę – atsijungus jie nesiunčiami."
        }
      ]
    }
  ],
  "en": [
    {
      "key": "about",
      "title": "About Gloumi",
      "items": [
        {
          "id": "K-1",
          "q": "What is Gloumi?",
          "a": "An app where you find beauty masters, see their work, prices and free times, and book a visit straight away. Masters provide the services in their own name; Gloumi is responsible for the app and payments in it."
        },
        {
          "id": "K-2",
          "q": "Is Gloumi free?",
          "a": "For clients, yes: you only pay the price the master sets, and Gloumi adds nothing. For masters, Starter costs €0 a month and Gloumi takes a commission; Pro and VIP Studio are paid plans."
        },
        {
          "id": "K-3",
          "q": "How do I contact support?",
          "a": "Side menu → Support → No answer here?, or info@gloumi.lt. About a specific visit – Report an issue in that visit. We confirm receipt within 2 working days and reply within 14 days, usually sooner."
        }
      ]
    },
    {
      "key": "account",
      "title": "Account",
      "items": [
        {
          "id": "K-4",
          "q": "How do I sign up and sign in?",
          "a": "On the sign-in screen tap Sign up: five steps and an email confirmation. You can also use Google, and Apple on iPhone. Sign in with your email or username and password, or with Google or Apple. You must be 14 or older."
        },
        {
          "id": "K-5",
          "q": "I forgot my password.",
          "a": "On the sign-in screen tap Forgot password, enter your email and open the link we send. Check your spam folder too. Signed up with Google or Apple? Sign in with the same button."
        },
        {
          "id": "K-6",
          "q": "The confirmation email did not arrive.",
          "a": "Check your spam folder. To get a new link: side menu → App settings → Account → Verify now next to your email."
        },
        {
          "id": "K-7",
          "q": "How do I change my details?",
          "a": "Name and bio – Profile → Edit profile; photo – tap it. Email, username and phone – side menu → App settings → Account. We can change your date of birth – write to us."
        },
        {
          "id": "K-8",
          "q": "How do I change the language or theme?",
          "a": "Side menu → App settings → Language / Kalba (Lithuanian or English) or App Theme. The change takes effect at once."
        },
        {
          "id": "K-10",
          "q": "How do I get a copy of my data?",
          "a": "Side menu → App settings → Account → Download my data – a JSON file without photo or voice files. For everything we hold, write to info@gloumi.lt from your account email – we reply within a month."
        },
        {
          "id": "K-11",
          "q": "Someone has got into my account.",
          "a": "Side menu → App settings → Account → Sign out everywhere, then Forgot password on the sign-in screen. Tell us what you did not do. Gloumi never asks for your password or a code."
        }
      ]
    },
    {
      "key": "visits",
      "title": "Visits",
      "items": [
        {
          "id": "K-12",
          "q": "How do I find a master?",
          "a": "Search: look for a service, master or salon, and use Filters or Map. Discover is a feed of masters' work."
        },
        {
          "id": "K-13",
          "q": "How do I book a visit?",
          "a": "On the master's profile tap Book a time, choose services, a date and time and how to pay, then tap Confirm Booking. You will be notified when the master confirms."
        },
        {
          "id": "K-14",
          "q": "When is my visit actually booked?",
          "a": "When the master confirms it: Pending Confirmation changes to Confirmed. Until then you can cancel any time and get a full refund. The same applies if the master declines."
        },
        {
          "id": "K-15",
          "q": "Every slot is taken – can I join a queue?",
          "a": "Yes. Pick the full day and tap Join the waitlist. If someone cancels that day, the first person in the queue is notified and can book the slot."
        },
        {
          "id": "K-16",
          "q": "What goes into the visit notes?",
          "a": "Whatever the master should know up front: previous formulas, colours, wishes. You can add a photo (Add vision). Tell the master about allergies or sensitivities directly."
        },
        {
          "id": "K-17",
          "q": "How do I cancel or move a visit?",
          "a": "Bookings → Cancel booking or Reschedule. Cancelling happens at once, with no second question. With less than 24 h to go before a confirmed visit, only the master can move it – message them."
        },
        {
          "id": "K-18",
          "q": "Will I get my money back if I cancel?",
          "a": "Cancel more than 24 h ahead, or if the master cancels – everything paid in the app is refunded. Cancel a confirmed visit later or do not turn up, and the deposit may stay with the master under their cancellation terms; the rest is refunded."
        },
        {
          "id": "K-19",
          "q": "When will a refund reach me?",
          "a": "We start the refund straight away, back to the way you paid. When it shows up depends on your bank. Still not there after a while? Write to us."
        },
        {
          "id": "K-20",
          "q": "The master did not turn up or the visit did not happen.",
          "a": "Paid in the app? Open the visit and tap Visit didn't happen? – up to 72 h after it ends. The master's payout is held and a person decides. Later, or if you paid on site – write to us."
        },
        {
          "id": "K-21",
          "q": "I am not happy with the service.",
          "a": "Message the master first – they provide the service. We help gather the facts and decide on the payment made in the app. If you cannot agree, you can contact the State Consumer Rights Protection Authority (vvtat.lt) for free."
        },
        {
          "id": "K-22",
          "q": "How do I leave a review?",
          "a": "Once the master marks the visit complete: Bookings → Completed procedures → Review professional. You have 48 h after the visit, and only for a visit that happened. A posted review cannot be edited – write to us."
        }
      ]
    },
    {
      "key": "payments",
      "title": "Payments",
      "items": [
        {
          "id": "K-23",
          "q": "How is a visit paid for?",
          "a": "The master chooses which payment methods to accept: Cash, Card at the salon or In the app. In the app you pay by card or Apple Pay, and Stripe emails you the receipt. A visit not paid within 30 min is cancelled."
        },
        {
          "id": "K-24",
          "q": "Is it safe to pay in the app?",
          "a": "Payments are handled by Stripe – Gloumi never sees or stores your card details. We never ask for your card number, codes or passwords by email or message."
        },
        {
          "id": "K-25",
          "q": "What is a deposit?",
          "a": "Part of the price – an amount or a percentage – that the master asks you to pay in the app when booking. It counts towards the price, and you pay the rest on site. When it is refunded – K-18."
        },
        {
          "id": "K-26",
          "q": "How do I leave a tip?",
          "a": "After a review of 3 stars or more, if the master accepts tips: 5, 10, 15% or €1–100, within 7 days of the visit. Later – Bookings → Completed procedures → Leave a tip. Gloumi takes nothing from tips."
        },
        {
          "id": "K-27",
          "q": "How do gift cards work?",
          "a": "Side menu → Gift card: buy one (€40–1,000) or tap I have a code to redeem. The amount becomes credit you apply when paying in the app. An unused card can be cancelled within 14 days – write to us."
        },
        {
          "id": "K-29",
          "q": "A master gave me their code – what do I do?",
          "a": "When booking, tap I have a master code, enter it and tap Apply, or open the master's link. Your price does not change."
        },
        {
          "id": "K-30",
          "q": "My bank shows the same amount twice.",
          "a": "Often it is a temporary hold that disappears within a few days. If you were charged twice, tell us when and how much you paid. Please do not send your card number."
        }
      ]
    },
    {
      "key": "masters",
      "title": "For masters",
      "items": [
        {
          "id": "K-31",
          "q": "How do I become a master?",
          "a": "Profile → Become a master: photo, name and city, description, field and agreeing to the terms. You must be 18 or older. Switch between client and master mode at the top of your profile."
        },
        {
          "id": "K-32",
          "q": "What do I need so that clients can book me?",
          "a": "Tap Add services and go through the wizard to Activate profile. You need services, working hours, fields and (if you work at a fixed place) an address; Taking bookings must be on."
        },
        {
          "id": "K-33",
          "q": "How do I add or change services?",
          "a": "Profile → Services and hours → Services and prices → New service. Deposit – Profile → Business → Payments → Ask for a deposit. Do not edit through “What services do you provide?” – it replaces your whole price list."
        },
        {
          "id": "K-34",
          "q": "How do I set working hours and days off?",
          "a": "Profile → Services and hours → Working hours → Weekly schedule. Mark a single day or a holiday by tapping the date in the calendar (I'm off this day). For a break from bookings, turn off Taking bookings."
        },
        {
          "id": "K-35",
          "q": "How do I block time or add a client myself?",
          "a": "Calendar → Block time – for one day or every week (a break). Add a visit – for your own client: confirmed at once, no deposit, and the client gets a notification."
        },
        {
          "id": "K-36",
          "q": "How do I confirm, reject, cancel or move a visit?",
          "a": "Calendar → Requests → Confirm or Reject – answer quickly. Cancel or move by opening the visit. If you cancel, the client gets everything back; move a visit only after agreeing with the client."
        },
        {
          "id": "K-37",
          "q": "How do I mark a visit complete?",
          "a": "Open the visit → Complete visit (from its start time). Afterwards answer “Did the client show up?” – otherwise it marks itself attended after 24 h. A client can review only a completed visit."
        },
        {
          "id": "K-38",
          "q": "How do I take payments in the app?",
          "a": "Profile → Business → Payments → Stripe payment settings → Turn on online payments; verify your identity in Stripe's window. If it is not finished within 30 days of a client's payment, the money goes back to the client."
        },
        {
          "id": "K-39",
          "q": "When do I get the money?",
          "a": "No earlier than 72 h after the visit ends, usually within 7 days, unless the client reported that it did not happen. To your bank on your Stripe payout schedule. Payouts are in Profile → Business → Payments."
        },
        {
          "id": "K-41",
          "q": "What is the master code?",
          "a": "Profile → Business → Payments → Code for your clients. Give it to clients from before Gloumi – no commission on them. Up to 50 clients, valid for 3 months. You may not give it to clients who found you through Gloumi."
        },
        {
          "id": "K-42",
          "q": "Why am I asked for my personal or company code and IBAN?",
          "a": "An EU rule, DAC7, requires platforms to report their sellers' income to the tax authority (VMI). Enter them in side menu → App settings → Business details. Clients never see them. If missing after 60 days, payouts are held."
        },
        {
          "id": "K-44",
          "q": "How do I cancel a subscription or get a refund?",
          "a": "In the store: iPhone – Settings → your name → Subscriptions; Android – Google Play → Payments & subscriptions → Subscriptions. On the App Store, at least 24 h before the period ends. Refunds are decided by Apple or Google. Deleting your account does not end the subscription."
        },
        {
          "id": "K-45",
          "q": "How do I create a salon?",
          "a": "Profile → Business → Salon → Create a salon (needs VIP Studio). Invite up to 10 masters by username. Members stay independent and get Pro features, and you see their visits."
        },
        {
          "id": "K-46",
          "q": "Can a review be removed?",
          "a": "We do not remove genuine negative reviews – only those that break the rules, are false or unrelated to the service; report those to info@gloumi.lt."
        },
        {
          "id": "K-47",
          "q": "A client reported that the visit did not happen.",
          "a": "The payout for the visit is held while we look into it. You can see the client's message – explain and, if we ask, send evidence. A person decides, and we tell you in the app and by email."
        },
        {
          "id": "K-48",
          "q": "My account has been restricted.",
          "a": "Our notice gives the reason and the rule. You can explain or appeal for free – via Support or info@gloumi.lt. A person reviews it and we reply in writing; an unjustified restriction is lifted at once."
        },
        {
          "id": "K-49",
          "q": "Can I rate a client?",
          "a": "Yes – after you complete a visit, the app offers Rate the client. Other masters see the rating; only they see the text. Rate honestly and only on that visit."
        }
      ]
    },
    {
      "key": "content",
      "title": "Content, notifications and safety",
      "items": [
        {
          "id": "K-50",
          "q": "How do I post a story or a photo of my work?",
          "a": "Pick a new story or post in the feed. Download an iCloud-only video to the phone first. One file – up to 60 MB, a story video – up to 1 min."
        },
        {
          "id": "K-51",
          "q": "How do I report inappropriate content or a person?",
          "a": "Press and hold a message → Report; on a master's profile – the icon at the top. Choose a reason → Send report. Reports are anonymous and our team reviews them. If someone is in danger, call 112."
        },
        {
          "id": "K-52",
          "q": "How do I block someone?",
          "a": "In the report sheet – Block user: you will no longer see their posts, stories or messages. To unblock: side menu → App settings → Blocked people."
        },
        {
          "id": "K-53",
          "q": "How do I manage notifications? Why do they not arrive?",
          "a": "The bell at the top: swipe left to delete, Edit for several at once. Not arriving? Allow Gloumi notifications in your phone settings and stay signed in – once you sign out, they stop."
        }
      ]
    }
  ]
};
