/**
 * Terms of Service and Privacy Policy – GENERATED by scripts/gen-from-app.mjs.
 *
 * Source of truth: gloumi-app/src/constants/legal.js in the Gloumi app
 * repository (version 1.7, 2026-09-26). The app shows this same text in
 * its LegalModal and App Store Connect points at the public copy, so the two
 * must never drift: change legal.js, then regenerate this file.
 *
 * The English text is a translation of the Lithuanian original; in case of
 * conflict the Lithuanian version prevails (stated in the source).
 */
export type LegalSection = {
  title: string;
  paragraphs?: string[];
  bullets?: string[];
};

export type LegalLang = "lt" | "en";

export const LEGAL_META = {
  "version": "1.7",
  "lastUpdated": "2026-09-26"
} as const;

export const LEGAL_DOCS: Record<LegalLang, { terms: LegalSection[]; privacy: LegalSection[] }> = {
  "lt": {
    "terms": [
      {
        "title": "Bendrosios nuostatos",
        "paragraphs": [
          "Šios naudojimosi taisyklės yra sutartis tarp Jūsų ir Gloumi. Sukurdami paskyrą arba naudodamiesi programėle Jūs patvirtinate, kad taisykles perskaitėte ir su jomis sutinkate.",
          "Naudotis Gloumi gali tik ne jaunesni nei 14 metų asmenys. Jaunesniems nei 18 metų naudotojams gali reikėti tėvų ar globėjų sutikimo."
        ]
      },
      {
        "title": "Gloumi vaidmuo",
        "paragraphs": [
          "Gloumi yra platforma, jungianti grožio paslaugų specialistus (meistrus) ir klientus. Gloumi pati grožio paslaugų neteikia ir nėra paslaugų sutarties tarp meistro ir kliento šalis."
        ],
        "bullets": [
          "Už paslaugos kokybę, saugą ir atitiktį atsako ją teikiantis meistras.",
          "Meistras pats atsako už veiklos registraciją, licencijas, higienos reikalavimus ir mokesčius.",
          "Gloumi neatsako už žalą, kilusią dėl netinkamai suteiktos paslaugos, tačiau tarpininkauja sprendžiant ginčus."
        ]
      },
      {
        "title": "Paskyra ir vaidmenys",
        "paragraphs": [
          "Registruojantis sukuriama kliento paskyra. Meistro funkcijos tampa prieinamos tik atskirai užpildžius ir pateikus meistro profilį.",
          "Jūs atsakote už savo prisijungimo duomenų saugumą ir už visus veiksmus, atliktus iš Jūsų paskyros. Apie neteisėtą prieigą privalote nedelsdami pranešti."
        ],
        "bullets": [
          "Draudžiama kurti paskyrą svetimu vardu ar teikti klaidingus duomenis.",
          "Vienam asmeniui leidžiama turėti vieną paskyrą.",
          "Gloumi gali paprašyti patvirtinti meistro tapatybę ar kvalifikaciją.",
          "Jaunesnis nei 18 metų naudotojas gali registruotis ir naršyti, bet mokamą vizitą ar avansą gali užsakyti tik turėdamas tėvų ar globėjų sutikimą. Meistro paskyrą gali susikurti tik pilnametis asmuo."
        ]
      },
      {
        "title": "Rezervacijos ir avansas",
        "paragraphs": [
          "Rezervacija laikoma sudaryta, kai meistras ją patvirtina programėlėje. Meistras gali nustatyti privalomą avansą – fiksuotą sumą arba procentą nuo paslaugos kainos.",
          "Sumokėtas avansas yra užskaitomas į galutinę paslaugos kainą."
        ],
        "bullets": [
          "Atšaukus vizitą likus daugiau nei 24 val., avansas grąžinamas.",
          "Atšaukus likus mažiau nei 24 val. arba neatvykus, avansas negrąžinamas.",
          "Jei vizitą atšaukia meistras, avansas grąžinamas visas.",
          "Vizito perkėlimo atveju avansas perkeliamas į naują laiką."
        ]
      },
      {
        "title": "Mokėjimai, komisinis ir išmokos meistrui",
        "paragraphs": [
          "Mokėjimus programėlėje vykdo Stripe. Gloumi kortelių duomenų nemato ir jų nesaugo. Meistras, norintis priimti mokėjimus per programėlę, susikuria Stripe paskyrą ir atlieka Stripe tapatybės patikrą; kol ji neužbaigta, išmokos nevykdomos.",
          "Nuo per programėlę sumokėtos sumos Gloumi išskaičiuoja komisinį mokestį. Jo dydis nurodomas meistro paskyroje prieš įjungiant mokėjimus ir prieš kiekvieną jo pakeitimą pranešama iš anksto. Likusi suma pervedama meistrui į jo Stripe paskyrą.",
          "Klientui komisinis nieko nekainuoja – jis išskaičiuojamas iš meistrui pervedamos sumos, o ne pridedamas prie paslaugos kainos."
        ],
        "bullets": [
          "Išmokos vykdomos tik po įvykusio vizito ir tik Stripe patvirtinus meistro tapatybę.",
          "Meistras pats atsako už mokesčius ir apskaitą nuo gautų pajamų. Gloumi nėra meistro mokesčių agentas.",
          "Grąžinus avansą klientui, grąžinama ir nuo jo išskaičiuoto komisinio dalis.",
          "Įtarus sukčiavimą Gloumi gali laikinai sustabdyti išmoką, kol aplinkybės išsiaiškinamos."
        ]
      },
      {
        "title": "Teisė atsisakyti sutarties",
        "paragraphs": [
          "Naudojimasis Gloumi klientui yra nemokamas, todėl atskiros sutarties su Gloumi, kurios būtų galima atsisakyti, nesudaroma. Žemiau – kaip 14 dienų taisyklė veikia tose vietose, kur mokama.",
          "Vizitas pas meistrą yra paslauga konkrečiai datai ir valandai. Tokioms paslaugoms vartotojo teisė per 14 dienų atsisakyti sutarties netaikoma (Civilinio kodekso 6.22810 str.). Vietoj jos galioja meistro atšaukimo sąlygos, rodomos prie jo anketos, ir bendra tvarka, aprašyta skyriuje „Rezervacijos ir avansas“.",
          "Meistro prenumerata perkama per Apple App Store arba Google Play. Pinigų grąžinimo klausimus sprendžia jie pagal savo taisykles, ir Gloumi negali jų grąžinti už juos – bet ir netrukdo kreiptis."
        ]
      },
      {
        "title": "Meistro prenumerata (Pro ir VIP Studio)",
        "paragraphs": [
          "Meistro funkcijos siūlomos kaip prenumerata dviem pakopomis – Pro ir VIP Studio. Kiekvieną pakopą galima mokėti kas mėnesį arba kas metus; kaina ir laikotarpis parodomi prieš pirkimą. Prenumerata perkama per Apple App Store arba Google Play ir automatiškai atsinaujina tam pačiam laikotarpiui, kol jos neatšaukiate.",
          "Naujas meistras 30 dienų gauna nemokamą bandomąjį laikotarpį su Pro funkcijomis. Jam pasibaigus, prenumerata savaime neprasideda ir nieko neapmokestinama – lieka nemokamas Starter planas.",
          "Prenumerata atšaukiama Jūsų App Store / Google Play paskyros nustatymuose ne vėliau kaip likus 24 val. iki laikotarpio pabaigos. Gloumi negali atšaukti prenumeratos už Jus."
        ],
        "bullets": [
          "Nepanaudotas bandomojo laikotarpio likutis dingsta įsigijus prenumeratą.",
          "Keičiant pakopą ar laikotarpį, kada pakeitimas įsigalioja ir kiek grąžinama už likusį laiką, sprendžia Apple arba Google pagal savo taisykles.",
          "Pinigų grąžinimo klausimus sprendžia Apple arba Google pagal savo taisykles.",
          "Pasibaigus prenumeratai, mokamos funkcijos išjungiamos, bet Jūsų duomenys išsaugomi."
        ]
      },
      {
        "title": "Turinys ir elgesio taisyklės",
        "paragraphs": [
          "Jūs išlaikote savo įkelto turinio (nuotraukų, „Stories“, aprašymų) autorių teises, bet suteikiate Gloumi neatlygintiną licenciją jį rodyti programėlėje."
        ],
        "bullets": [
          "Draudžiama kelti svetimą turinį be leidimo.",
          "Draudžiamas įžeidžiantis, diskriminuojantis ar erotinio pobūdžio turinys.",
          "Draudžiamas smurtą vaizduojantis ar jį skatinantis turinys.",
          "Draudžiama priekabiauti, grasinti ar tyčia sekti kitą naudotoją.",
          "Draudžiama skatinti ar padėti vykdyti neteisėtą veiklą.",
          "Draudžiamas nepageidaujamas reklaminis turinys, grandininiai laiškai ir piramidės.",
          "Draudžiama skelbti kito asmens kontaktus, adresą ar kitus asmens duomenis be jo sutikimo – taip pat ir atsiliepime.",
          "Draudžiama kelti kitų asmenų nuotraukas be jų sutikimo.",
          "Jei nuotraukoje matomas jaunesnis nei 18 metų asmuo, ją kelti galima tik turint jo tėvų ar globėjų sutikimą.",
          "Keldami turinį patvirtinate, kad turite visas reikalingas teises į jį ir kad jis nepažeidžia trečiųjų asmenų teisių. Jei dėl Jūsų įkelto turinio Gloumi pareiškiamos pretenzijos, atsakote už jas Jūs.",
          "Gloumi gali pašalinti taisyklių neatitinkantį turinį be išankstinio įspėjimo."
        ]
      },
      {
        "title": "Atsiliepimai",
        "paragraphs": [
          "Atsiliepimą palikti gali tik klientas, kurio vizitas pas tą meistrą realiai įvyko. Atsiliepimas turi būti sąžiningas ir remtis asmenine patirtimi.",
          "Meistras gali į atsiliepimą atsakyti viešai. Neigiamas atsiliepimas savaime nėra pagrindas jį šalinti: Gloumi šalina tik tuos, kurie pažeidžia elgesio taisykles, yra melagingi, įžeidžiantys arba nesusiję su suteikta paslauga.",
          "Draudžiama rašyti atsiliepimus apie save ar savo konkurentus, taip pat siūlyti klientui atlygį už atsiliepimą ar jo pašalinimą."
        ]
      },
      {
        "title": "Gloumi intelektinė nuosavybė ir draudžiami veiksmai",
        "paragraphs": [
          "Programėlė, jos pavadinimas, logotipas, dizainas, tekstai, piktogramos ir programinis kodas priklauso Gloumi arba naudojami pagal licenciją. Naudodamiesi programėle Jūs gaunate teisę ja naudotis asmeniniais tikslais – bet ne teisę ją kopijuoti ar perdirbti."
        ],
        "bullets": [
          "Draudžiama kopijuoti, platinti ar viešai skelbti programėlės turinį komerciniais tikslais be rašytinio Gloumi sutikimo.",
          "Draudžiama automatiškai rinkti duomenis (robotai, „scraping“), kurti programėlės kopijas ar išvestinius kūrinius.",
          "Draudžiama bandyti apeiti saugumo priemones, jungtis prie svetimų paskyrų, perkrauti sistemą ar platinti kenkėjišką kodą.",
          "Draudžiama naudoti Gloumi pavadinimą ar logotipą taip, kad susidarytų įspūdis apie partnerystę, kurios nėra."
        ]
      },
      {
        "title": "Rekomendacijų kreditas ir dovanų kortelės",
        "paragraphs": [
          "Pakvietus naują naudotoją pagal savo kodą, abu gaunate kreditą, kurio dydis nurodomas kvietimo ekrane. Kreditas užskaitomas tik tada, kai pakviestasis realiai įvykdo pirmą vizitą – vien registracijos nepakanka.",
          "Dovanų kortelę galima įsigyti nuo 40 iki 1000 eurų. Panaudota kortelė virsta tokiu pat kreditu paskyroje."
        ],
        "bullets": [
          "Kreditas naudojamas tik atsiskaitant programėlėje. Į pinigus jis nekeičiamas ir kitam asmeniui neperleidžiamas.",
          "Kreditas negalioja jokio termino ir savaime nepradingsta.",
          "Vienam asmeniui – viena paskyra ir vienas kodas. Kurti papildomas paskyras kreditui gauti draudžiama.",
          "Įtarę, kad kreditas gautas apgaule (netikros paskyros, susitarimai, masinis kodo platinimas), galime jį atšaukti ir apriboti paskyrą.",
          "Programos sąlygas ir kredito dydį galime keisti ar programą nutraukti; jau suteiktas kreditas lieka galioti.",
          "Neišnaudotą ir nepanaudotą dovanų kortelę galima atšaukti per 14 dienų nuo pirkimo. Panaudojus ją bent iš dalies, pinigai negrąžinami."
        ]
      },
      {
        "title": "Kainos ir jų klaidos",
        "paragraphs": [
          "Paslaugų kainas nustato meistras ir gali jas keisti. Jums galioja ta kaina, kuri buvo rodoma rezervacijos patvirtinimo metu.",
          "Jei dėl akivaizdžios klaidos rodoma kaina buvo aiškiai neteisinga (pvz., 1 € vietoj 100 €), rezervacija neįsigalioja automatiškai: apie tai pranešame, pasiūlome patvirtinti teisingą kainą arba grąžiname sumokėtą avansą visą."
        ]
      },
      {
        "title": "Neteisėto turinio pranešimas ir sprendimų apskundimas",
        "paragraphs": [
          "Gloumi yra tarpininkavimo paslauga pagal ES Skaitmeninių paslaugų aktą (Reglamentas 2022/2065). Kontaktinis taškas naudotojams ir institucijoms – info@gloumi.lt; susirašinėjame lietuvių ir anglų kalbomis.",
          "Apie neteisėtą turinį galite pranešti tuo pačiu adresu arba per programėlės pranešimo apie turinį mygtuką. Pranešime nurodykite, kur tas turinys yra ir kodėl, Jūsų manymu, jis neteisėtas. Gavę pranešimą jį išnagrinėjame ir apie sprendimą informuojame pranešėją.",
          "Pranešimus nagrinėjame nedelsdami – paprastai per kelias darbo dienas, o akivaizdžiai žalingą turinį pašaliname iš karto. Pranešti apie turinį galima per 6 mėnesius nuo jo pastebėjimo.",
          "Pašalinę turinį arba apriboję paskyrą, nurodome priežastį ir taisyklės punktą, kuriuo remiamės. Su sprendimu nesutinkantis naudotojas per 6 mėnesius gali jį apskųsti rašydamas info@gloumi.lt; skundą nagrinėja žmogus, o ne automatinė sistema, ir apie rezultatą pranešame.",
          "Jei sprendimas Jūsų netenkina ir po apskundimo, galite kreiptis į ginčų sprendimo ne teismo tvarka instituciją arba į teismą. Teisė kreiptis į teismą išlieka visada."
        ]
      },
      {
        "title": "Kaip rikiuojami rezultatai",
        "paragraphs": [
          "Kad būtų aišku, kodėl vienas meistras rodomas anksčiau už kitą, žemiau surašyti pagrindiniai parametrai. Tų pačių parametrų laikomės ir prieš meistrus – jie taikomi visiems vienodai."
        ],
        "bullets": [
          "Paieškos rezultatus lemia Jūsų pačių pasirinkti filtrai: kategorija, miestas, atstumas, kainų rėžis, įvertinimas ir laisvi laikai. Rezultatai nėra pritaikomi asmeniškai pagal Jūsų ankstesnį elgesį.",
          "Srautą sudaro paskutinių 21 dienos įrašai, ir jų eilę lemia keli dalykai kartu. Daugiausia sveria tai, kaip į įrašą reagavo kiti per pastarąsias 7 dienas: paspaudimas rezervuoti, išsaugojimas, pasidalijimas, komentaras, ilgesnis žiūrėjimas ir patiktukas. Prie to pridedamas meistro įvertinimas (skaičiuojamas nuo trijų atsiliepimų), atimama atšauktų vizitų dalis, o turintis laisvų laikų rodomas kiek aukščiau. Visa tai mažėja su laiku: įrašo svoris perpus sumažėja maždaug per 36 valandas, tad šviežias įrašas pakyla ir be didelio dėmesio.",
          "Kad sraute matytumėte skirtingus meistrus, iš vieno meistro rodomi ne daugiau kaip keturi naujausi jo įrašai, o nuo trečiojo kiekvienas kitas sveria mažiau. Įrašai, kuriuos jau matėte, nustumiami žemyn.",
          "Srautas pritaikomas asmeniškai, ir tai remiasi Jūsų pačių veiksmais ir nustatymais: meistrų, kuriuos sekate, įrašai rodomi aukščiau; jei domitės kuria nors sritimi, tos srities įrašai taip pat rodomi aukščiau; o jei leidote naudoti vietą, arčiau Jūsų (iki 15 km) esančių meistrų įrašai pakeliami – be vietos atstumas skaičiuojamas nuo Vilniaus centro. Skiltis „Sekami“ rodo tą patį srautą, tik palikdama vien sekamų meistrų įrašus; kitaip ji nerikiuoja.",
          "Vietos rezultatuose NEGALIMA nusipirkti. Gloumi neparduoda reklamos ir nekelia meistro aukščiau už mokestį; prenumerata atrakina funkcijas, bet ne poziciją sąraše.",
          "Atsiliepimų vidurkis rodomas toks, koks yra; jo nekoreguojame ir neslepiame prastesnių."
        ]
      },
      {
        "title": "Meistras yra verslininkas",
        "paragraphs": [
          "Meistras, siūlantis paslaugas per Gloumi, veikia kaip verslininkas savo vardu. Tai reiškia, kad sudarydami vizito sutartį Jūs turite visas vartotojo teises pagal Lietuvos Respublikos teisę, ir jas įgyvendinate meistro, o ne Gloumi, atžvilgiu.",
          "Jei paslaugą kada nors siūlytų asmuo, kuris nėra verslininkas, prie jo anketos tai būtų nurodyta atskirai – tokiu atveju vartotojų teisės apsaugos taisyklės Jums negaliotų.",
          "Gloumi nėra vizito sutarties šalis, tačiau atsako už tai, kas yra jos pusėje: už programėlę, per ją atliktus mokėjimus ir už tai, kad meistro anketoje pateikta informacija būtų tokia, kokią jis pats nurodė."
        ]
      },
      {
        "title": "Kaip tikriname atsiliepimus",
        "paragraphs": [
          "Visi rodomi atsiliepimai yra patikrinti, ir tai ne pažadas, o tai, kaip veikia duomenų bazė. Atsiliepimą įrašyti gali tik tas naudotojas, kurio vizitas pas tą meistrą yra pažymėtas kaip įvykęs; be tokio įrašo duomenų bazė atsiliepimo tiesiog nepriima. Todėl atsiliepimų „iš šalies“ čia nebūna.",
          "Atsiliepimus galima palikti tik pasibaigus vizitui ir tam skirtą laikotarpį. Atsiliepimų neperkame, neužsakome ir už juos neatsilyginame, taip pat neleidžiame to daryti meistrams."
        ]
      },
      {
        "title": "Meistrams: sąlygų keitimas, ribojimas ir skundai",
        "paragraphs": [
          "Meistras naudojasi Gloumi kaip verslo naudotojas, todėl jam papildomai galioja ES reglamentas 2019/1150 dėl tarpininkavimo paslaugų skaidrumo. Žemiau – kas iš to seka."
        ],
        "bullets": [
          "Apie šių taisyklių pakeitimus meistrui pranešame ne vėliau kaip prieš 15 dienų. Jei nesutinkate, per tą laiką galite nutraukti naudojimąsi be jokių pasekmių.",
          "Prieš apribodami ar sustabdydami meistro paskyrą, nurodome priežastis raštu ir suteikiame galimybę paaiškinti aplinkybes. Nutraukdami paslaugą visiškai, pranešame prieš 30 dienų, išskyrus atvejus, kai to neleidžia teisės aktai arba kai pažeidimas kartojasi ar kelia tiesioginę žalą.",
          "Duomenys, kuriuos meistras sukaupia naudodamasis Gloumi – klientų sąrašas, vizitų istorija, pajamos – priklauso jam ir yra pasiekiami programėlėje. Nutraukus paskyrą jie pateikiami paprašius.",
          "Skundą dėl mūsų sprendimo meistras siunčia info@gloumi.lt. Gloumi yra maža įmonė, todėl reglamento 11 ir 12 straipsniai (vidinė skundų sistema ir tarpininkai) mums netaikomi – bet skundus nagrinėjame, atsakome raštu ir nurodome pagrindą.",
          "Gloumi neteikia grožio paslaugų ir nekonkuruoja su meistrais. Savų paslaugų sąraše nekeliame ir jokiam meistrui palankesnių sąlygų netaikome."
        ]
      },
      {
        "title": "Paskyros ribojimas ir nutraukimas",
        "paragraphs": [
          "Gloumi gali laikinai apriboti arba panaikinti paskyrą, jei pažeidžiamos šios taisyklės arba veikla kelia žalą kitiems naudotojams.",
          "Jūs galite bet kada ištrinti savo paskyrą programėlės nustatymuose. Ištrynus paskyrą, būsimos rezervacijos atšaukiamos."
        ]
      },
      {
        "title": "Atsakomybės ribojimas",
        "paragraphs": [
          "Programėlė teikiama „tokia, kokia yra“. Gloumi nesuteikia garantijų dėl nepertraukiamo veikimo ar klaidų nebuvimo.",
          "Gloumi atsakomybė ribojama tiek, kiek tai leidžia Lietuvos Respublikos teisė. Šios nuostatos neriboja Jūsų kaip vartotojo teisių pagal imperatyvias teisės normas."
        ]
      },
      {
        "title": "Skundai ir ginčų sprendimas",
        "paragraphs": [
          "Jei kas nors nepavyko, pirmiausia parašykite mums per programėlės skiltį „Pagalba“ arba adresu info@gloumi.lt. Kreipimąsi patvirtiname per 2 darbo dienas ir stengiamės atsakyti iš esmės per 14 kalendorinių dienų.",
          "Ginčus dėl pačios paslaugos kokybės sprendžia klientas ir meistras tarpusavyje – Gloumi paslaugos neteikia. Mes padedame surinkti faktus (rezervacijos įrašą, susirašinėjimą, mokėjimo duomenis) ir sprendžiame tai, kas priklauso nuo mūsų: per programėlę atliktus mokėjimus, avansą ir paskyros veiksmus.",
          "Nepavykus susitarti, vartotojas gali kreiptis į Valstybinę vartotojų teisių apsaugos tarnybą (vvtat.lt) – tai ne teismo tvarka nagrinėjanti institucija, ir kreipimasis į ją nemokamas. Teisė kreiptis į teismą išlieka visada."
        ]
      },
      {
        "title": "Taisyklių keitimas ir taikoma teisė",
        "paragraphs": [
          "Apie esminius taisyklių pakeitimus pranešime programėlėje arba el. paštu ne vėliau kaip prieš 14 dienų iki jų įsigaliojimo. Toliau naudodamiesi Gloumi po pakeitimų įsigaliojimo, Jūs su jais sutinkate; nesutikdami galite ištrinti paskyrą, ir tai Jums nieko nekainuos.",
          "Pranešimus siunčiame paskyroje nurodytu el. paštu arba rodome programėlėje. Jūs mums rašote adresu info@gloumi.lt.",
          "Jei kuri nors šių taisyklių nuostata būtų pripažinta negaliojančia, likusios lieka galioti, o negaliojančią pakeisime artimiausia teisėta nuostata.",
          "Gloumi gali perleisti savo teises ir pareigas pagal šias taisykles kitam juridiniam asmeniui (pvz., įmonių reorganizavimo atveju). Jūsų teisės nuo to nesumažėja, ir apie tai pranešame iš anksto.",
          "Sutarčiai taikoma Lietuvos Respublikos teisė. Šios nuostatos neatima iš Jūsų teisių, kurias vartotojui suteikia jo nuolatinės gyvenamosios vietos valstybės imperatyvios normos. Ginčai sprendžiami derybomis, o nepavykus – Lietuvos Respublikos teismuose."
        ]
      }
    ],
    "privacy": [
      {
        "title": "Kas tvarko Jūsų duomenis",
        "paragraphs": [
          "Jūsų asmens duomenis tvarko Gloumi kaip duomenų valdytojas. Duomenys tvarkomi pagal Bendrąjį duomenų apsaugos reglamentą (BDAR / GDPR).",
          "Yra viena išimtis, ir ji svarbi. Tai, ką meistras užsirašo APIE JUS savo privačiose pastabose, jis renka savo tikslais – ten duomenų valdytojas yra meistras, o Gloumi tik saugo tuos įrašus jo pavedimu. Dėl tokių pastabų kreipkitės į patį meistrą; jei jis neatsako, parašykite mums ir mes padėsime susisiekti.",
          "Duomenų apsaugos pareigūno Gloumi neturi ir pagal BDAR 37 str. neprivalo turėti. Visais duomenų klausimais rašykite info@gloumi.lt – atsakome per vieną mėnesį, o sudėtingesniais atvejais galime pratęsti dar dviem mėnesiams, apie tai pranešdami."
        ]
      },
      {
        "title": "Kokius duomenis renkame",
        "paragraphs": [
          "Renkame tik tuos duomenis, kurie reikalingi programėlės veikimui:"
        ],
        "bullets": [
          "Paskyros duomenys: vardas, naudotojo vardas, el. paštas, telefono numeris (neprivalomas), gimimo data, lytis (neprivaloma), profilio nuotrauka.",
          "Meistro duomenys: paslaugų sąrašas, kainos, darbo laikas, miestas, portfolio nuotraukos.",
          "Rezervacijų duomenys: pasirinkta paslauga, data, laikas, statusas, avanso informacija.",
          "Turinys: „Stories“, įrašai, atsiliepimai, susirašinėjimo žinutės.",
          "Vietos duomenys: apytikslė arba tiksli buvimo vieta – tik jei suteikiate leidimą. Ji naudojama artimiausių meistrų paieškai ir srauto rikiavimui (arčiau esančių meistrų įrašai rodomi aukščiau). Paskutinė žinoma vieta saugoma Jūsų paskyroje ir kitiems naudotojams nerodoma.",
          "Techniniai duomenys: įrenginio tipas, OS versija, pranešimų žetonas (push token), klaidų ataskaitos."
        ]
      },
      {
        "title": "Kodėl ir kokiu pagrindu",
        "paragraphs": [
          "Duomenis tvarkome šiais tikslais ir teisiniais pagrindais:"
        ],
        "bullets": [
          "Sutarties vykdymas – paskyros administravimas, rezervacijos, mokėjimai.",
          "Sutikimas – vietos nustatymas, pranešimai, rinkodaros žinutės. Sutikimą galite bet kada atšaukti.",
          "Teisėtas interesas – saugumas, sukčiavimo prevencija, paslaugos tobulinimas.",
          "Teisinė prievolė – apskaitos ir mokestiniai reikalavimai.",
          "Gimimo data tvarkoma tik amžiaus ribai patikrinti (žr. „Vaikų privatumas“). Kitiems naudotojams ji nematoma.",
          "Lytis (neprivaloma) tvarkoma Jūsų sutikimu: pagal ją meistro pareigos rašomos teisinga gimine („Meistrė“ / „Meistras“), o turinio rekomendacijos gali būti pritaikomos Jums. Kliento lytis kitiems naudotojams nerodoma. Pasirinkus „Nenoriu nurodyti“, nurodyta lytis ištrinama."
        ]
      },
      {
        "title": "Ar duomenis privaloma pateikti",
        "paragraphs": [
          "Dalis duomenų yra būtina sutarčiai vykdyti, ir be jų paslauga tiesiog neveiktų. El. pašto adresas reikalingas paskyrai ir pranešimams apie rezervaciją; vardas – kad meistras žinotų, ko laukti; gimimo data – amžiaus ribai patikrinti. Jų nepateikus paskyros sukurti negalėsime.",
          "Visa kita yra Jūsų pasirinkimas, ir jo nepasirinkus prarandama tik ta viena funkcija: be telefono numerio meistras negalės paskambinti, be vietos nustatymo nerodysime artimiausių meistrų (o atstumą sraute skaičiuosime nuo Vilniaus centro), be pranešimų leidimo negausite priminimo apie vizitą.",
          "Duomenis tvarkome laikydamiesi BDAR principų: tik aiškiai nurodytais tikslais, tik tiek, kiek jų tam reikia, ne ilgiau nei reikia, ir taip, kad jie būtų tikslūs ir saugūs."
        ]
      },
      {
        "title": "Iš kur gauname duomenis, kurių neduodate mums patys",
        "paragraphs": [
          "Daugumą duomenų pateikiate Jūs pats. Bet dalis atkeliauja kitaip, ir apie tai turite žinoti:"
        ],
        "bullets": [
          "Iš meistro – kai jis pats užrašo Jus vizitui arba pasižymi privačią pastabą apie Jus.",
          "Iš kito naudotojo – kai jis pažymi Jus savo įraše ar „Story“ arba parašo atsiliepimą apie Jus kaip klientą.",
          "Iš Apple ar Google – prisijungiant per jų paskyrą gauname vardą ir el. pašto adresą (Apple atveju – ir paslėptą persiuntimo adresą, jei taip pasirenkate).",
          "Iš Stripe – mokėjimo būsena, grąžinimai ir meistro tapatybės patikros rezultatas. Kortelės numerio negauname.",
          "Iš paties įrenginio – techniniai duomenys ir klaidų ataskaitos, kai programėlė nulūžta."
        ]
      },
      {
        "title": "Kam perduodame duomenis",
        "paragraphs": [
          "Duomenų neparduodame. Jie perduodami tik paslaugų teikėjams, kurie padeda mums veikti:"
        ],
        "bullets": [
          "Supabase – paskyrų autentifikacija ir duomenų bazė.",
          "Cloudflare R2 – nuotraukų, vaizdo įrašų ir balso žinučių saugojimas.",
          "Stripe – mokėjimų vykdymas, išmokos meistrams ir meistro tapatybės patikra (KYC).",
          "Expo – push pranešimų pristatymas į įrenginį.",
          "Apple / Google – prisijungimas per Apple ar Google paskyrą ir prenumeratų apdorojimas.",
          "Sentry – klaidų ataskaitų surinkimas, kad galėtume pataisyti programėlės gedimus. Duomenys saugomi ES.",
          "RevenueCat – meistro prenumeratos pirkimo patikra ir jos būsena. Gauna Jūsų paskyros identifikatorių ir pirkimo duomenis iš App Store ar Google Play; mokėjimo kortelės duomenų negauna nei jie, nei mes.",
          "Meistrui, pas kurį registruojatės, matomas Jūsų vardas, nuotrauka, kontaktai ir vizitų istorija."
        ]
      },
      {
        "title": "Duomenų perdavimas už Europos ekonominės erdvės ribų",
        "paragraphs": [
          "Dalis aukščiau išvardytų paslaugų teikėjų yra arba turi infrastruktūros už EEE ribų, daugiausia Jungtinėse Amerikos Valstijose. Tai reiškia, kad dalis duomenų ten pasiekiama arba ten saugoma.",
          "Tokie perdavimai vykdomi remiantis Europos Komisijos patvirtintomis standartinėmis sutarčių sąlygomis, o kur taikoma – ir ES ir JAV duomenų privatumo sistema (Data Privacy Framework). Su tiekėjais esame sudarę duomenų tvarkymo sutartis, kurios juos saisto tvarkyti duomenis tik pagal mūsų nurodymus.",
          "Sentry klaidų ataskaitos saugomos ES. Nuotraukos ir vaizdo įrašai Cloudflare R2 saugomi ES regione.",
          "Standartinių sutarčių sąlygų kopiją galite gauti parašę info@gloumi.lt."
        ]
      },
      {
        "title": "Automatizuoti sprendimai ir profiliavimas",
        "paragraphs": [
          "Automatizuotų sprendimų, kurie Jums sukeltų teisinių pasekmių ar panašiai reikšmingai Jus paveiktų (BDAR 22 str.), Gloumi nepriima. Paskyros neužblokuoja ir mokėjimo neatmeta vien algoritmas – už tokį sprendimą visada atsako žmogus.",
          "Rodymo eilė nėra sprendimas apie Jus, bet ji irgi turi būti aiški – kokie parametrai ją lemia, surašyta naudojimosi taisyklių skyriuje „Kaip rikiuojami rezultatai“.",
          "Reklamos profilių nekuriame ir duomenų reklamos tinklams neperduodame."
        ]
      },
      {
        "title": "Meistro privatūs užrašai",
        "paragraphs": [
          "Meistras gali kurti privačias pastabas apie klientą (pvz., dažų formules ar pageidavimus). Šios pastabos matomos tik jas sukūrusiam meistrui. Programėlė neprašo sveikatos duomenų ir neturi jiems skirto lauko. Meistras atsako už tai, kad pastabose nebūtų perteklinių ar jautrių duomenų, įskaitant sveikatos, be Jūsų sutikimo."
        ]
      },
      {
        "title": "Kiek laiko saugome",
        "bullets": [
          "Paskyros duomenys – kol paskyra aktyvi, ir 30 dienų po ištrynimo.",
          "Rezervacijų ir mokėjimų įrašai – iki 10 metų (apskaitos reikalavimai).",
          "Susirašinėjimo žinutės – kol paskyra aktyvi arba kol jas ištrinate.",
          "„Stories“ – automatiškai nustoja būti rodomos po 24 valandų."
        ],
        "paragraphs": []
      },
      {
        "title": "Jūsų teisės",
        "paragraphs": [
          "Pagal BDAR turite teisę:"
        ],
        "bullets": [
          "susipažinti su savo duomenimis ir gauti jų kopiją;",
          "reikalauti ištaisyti netikslius duomenis;",
          "reikalauti ištrinti duomenis („teisė būti pamirštam“);",
          "apriboti tvarkymą arba jam nesutikti;",
          "perkelti duomenis kitam paslaugų teikėjui;",
          "atšaukti duotą sutikimą;",
          "pateikti skundą Valstybinei duomenų apsaugos inspekcijai (vdai.lrv.lt)."
        ]
      },
      {
        "title": "Duomenų sauga",
        "paragraphs": [
          "Duomenys perduodami šifruotu ryšiu (TLS). Paskyrų ir rezervacijų duomenys saugomi Supabase infrastruktūroje su eilučių lygio prieigos taisyklėmis, o nuotraukos ir kiti failai – Cloudflare R2 saugykloje. Slaptažodžiai saugomi tik šifruotos santraukos pavidalu – jų nematome.",
          "Nė viena sistema nėra visiškai saugi, todėl rekomenduojame naudoti unikalų slaptažodį."
        ]
      },
      {
        "title": "Vaikų privatumas",
        "paragraphs": [
          "Gloumi neskirta jaunesniems nei 14 metų asmenims. 14 metų yra Lietuvoje nustatyta riba, nuo kurios vaikas gali pats duoti sutikimą dėl informacinės visuomenės paslaugų (BDAR 8 str. 1 d.). Registruojantis prašome nurodyti gimimo datą ir jaunesnių paskyrų nekuriame. Sužinoję, kad tokio amžiaus asmens duomenys vis dėlto buvo surinkti, juos nedelsdami ištrinsime."
        ]
      },
      {
        "title": "Slapukai ir vietinė saugykla",
        "paragraphs": [
          "Gloumi yra programėlė, o ne svetainė, todėl įprastų naršyklės slapukų ji nenaudoja. Tačiau dalis duomenų saugoma pačiame įrenginyje, ir apie tai turite žinoti tiek pat."
        ],
        "bullets": [
          "Prisijungimo sesija: saugoma įrenginio saugykloje (iOS Keychain, Android Keystore), šifruota operacinės sistemos priemonėmis. Reikalinga tam, kad nereikėtų prisijungti iš naujo kaskart atidarius programėlę.",
          "Turinio talpykla: paskutinis srautas, „Stories\" ir paveikslėliai laikomi įrenginyje, kad programėlė atsidarytų greitai ir veiktų prastame ryšyje. Atsijungus ji išvaloma.",
          "Nustatymai: kalba, temos pasirinkimas ir panašūs pasirinkimai.",
          "Nė vienas iš šių įrašų nėra naudojamas sekimui ar reklamai, ir jie nėra perduodami tretiesiems asmenims. Ištrynus programėlę, ištrinami ir jie."
        ]
      },
      {
        "title": "Rinkodaros žinutės",
        "paragraphs": [
          "Naujienas ir pasiūlymus siunčiame tik gavę Jūsų sutikimą. Sutikimą galite atšaukti bet kada – programėlės pranešimų nustatymuose arba paspaudę atsisakymo nuorodą laiške; nuo to niekas kita paskyroje nepasikeis.",
          "Atskirai nuo rinkodaros siunčiame tarnybinius pranešimus – apie rezervaciją, jos pakeitimą, mokėjimą ar saugumą. Jų atsisakyti negalima, nes be jų paslauga neveiktų."
        ]
      },
      {
        "title": "Duomenų saugumo pažeidimai",
        "paragraphs": [
          "Jei įvyktų asmens duomenų saugumo pažeidimas, apie jį pranešime Valstybinei duomenų apsaugos inspekcijai per 72 valandas nuo sužinojimo. Jei pažeidimas keltų didelę riziką Jūsų teisėms, pranešime ir Jums asmeniškai – aiškiai ir be delsimo, kartu nurodydami, ką patiems verta padaryti."
        ]
      },
      {
        "title": "Atšaukimas ir pinigų grąžinimas",
        "paragraphs": [
          "Konkrečias atšaukimo sąlygas nustato pats meistras ir jos rodomos prie jo anketos. Žemiau – bendra tvarka, galiojanti, kai meistras nenurodo kitaip."
        ],
        "bullets": [
          "Atšaukus likus daugiau nei 24 val. iki vizito, sumokėtas avansas grąžinamas visas.",
          "Atšaukus vėliau nei prieš 24 val. arba neatvykus, avansas negrąžinamas – jis dengia meistro rezervuotą ir nebeparduodamą laiką.",
          "Meistrui atšaukus vizitą, avansas grąžinamas visas, nepriklausomai nuo laiko.",
          "Pinigai grąžinami tuo pačiu būdu, kuriuo buvo sumokėti. Grąžinimą inicijuojame nedelsdami; kiek užtruks lėšos jūsų sąskaitoje, priklauso nuo banko ar kortelės išdavėjo.",
          "Likusią sumos dalį už paslaugą mokate salone – ji per programėlę nenuskaitoma ir jos grąžinimo klausimai sprendžiami su meistru.",
          "Gloumi neteikia grožio paslaugų ir nesprendžia ginčų dėl jų kokybės; mūsų atsakomybė apsiriboja per programėlę atliktu mokėjimu."
        ]
      }
    ]
  },
  "en": {
    "terms": [
      {
        "title": "General provisions",
        "paragraphs": [
          "These terms of use form an agreement between you and Gloumi. By creating an account or using the app you confirm that you have read and accepted these terms.",
          "Gloumi may only be used by people aged 14 or over. Users under 18 may need the consent of a parent or guardian."
        ]
      },
      {
        "title": "The role of Gloumi",
        "paragraphs": [
          "Gloumi is a platform that connects beauty professionals (masters) with clients. Gloumi does not provide beauty services itself and is not a party to the service contract between the master and the client."
        ],
        "bullets": [
          "The master providing the service is responsible for its quality, safety and compliance.",
          "The master is responsible for their own business registration, licences, hygiene requirements and taxes.",
          "Gloumi is not liable for damage caused by an improperly provided service, but will mediate in resolving disputes."
        ]
      },
      {
        "title": "Account and roles",
        "paragraphs": [
          "Registration creates a client account. Master features become available only after a master profile is separately filled in and submitted.",
          "You are responsible for keeping your login details secure and for all activity carried out from your account. You must report unauthorised access without delay."
        ],
        "bullets": [
          "Creating an account under someone else’s name or providing false data is prohibited.",
          "One person may hold one account.",
          "Gloumi may ask a master to confirm their identity or qualifications.",
          "A user under 18 may register and browse, but may book a paid visit or pay a deposit only with the consent of a parent or guardian. Only an adult may create a master account."
        ]
      },
      {
        "title": "Payments, commission and payouts to masters",
        "paragraphs": [
          "Payments in the app are processed by Stripe. Gloumi never sees or stores your card details. A master who wants to accept payments through the app creates a Stripe account and completes Stripe identity verification; until that is finished, no payouts are made.",
          "Gloumi deducts a commission from the amount paid through the app. Its rate is shown in the master account before payments are switched on, and any change to it is announced in advance. The remainder is transferred to the master account at Stripe.",
          "The commission costs the client nothing: it is deducted from what is paid out to the master, not added to the price of the service."
        ],
        "bullets": [
          "Payouts are made only after the visit has taken place and only once Stripe has verified the master identity.",
          "The master is responsible for their own taxes and accounting on the income received. Gloumi is not the master tax agent.",
          "If a deposit is refunded to the client, the share of commission taken from it is refunded too.",
          "Where fraud is suspected, Gloumi may hold a payout while the circumstances are established."
        ]
      },
      {
        "title": "Right of withdrawal",
        "paragraphs": [
          "Using Gloumi is free for clients, so there is no separate paid contract with Gloumi to withdraw from. Below is how the 14-day rule works in the places where money does change hands.",
          "A visit to a master is a service for a specific date and time. For such services the consumer 14-day right of withdrawal does not apply (Art. 16(l) of Directive 2011/83/EU, implemented in Lithuania by Art. 6.22810 of the Civil Code). What applies instead is the cancellation policy of the master, shown on their profile, and the general rule described under Bookings and deposits.",
          "The master subscription is bought through the Apple App Store or Google Play. Refunds are handled by them under their own rules; Gloumi cannot issue those refunds on their behalf, but will not stand in the way of a request."
        ]
      },
      {
        "title": "Bookings and deposits",
        "paragraphs": [
          "A booking is considered made once the master confirms it in the app. A master may require a deposit – either a fixed amount or a percentage of the service price.",
          "A paid deposit is credited towards the final price of the service."
        ],
        "bullets": [
          "If a visit is cancelled more than 24 hours in advance, the deposit is refunded.",
          "If it is cancelled less than 24 hours in advance, or in case of a no-show, the deposit is not refunded.",
          "If the master cancels the visit, the deposit is refunded in full.",
          "If a visit is rescheduled, the deposit is carried over to the new time."
        ]
      },
      {
        "title": "Master subscription (Pro and VIP Studio)",
        "paragraphs": [
          "Master features are offered as a subscription in two tiers, Pro and VIP Studio. Each tier can be paid monthly or yearly; the price and the period are shown before you buy. The subscription is purchased through the Apple App Store or Google Play and renews automatically for the same period until you cancel it.",
          "A new master gets a free 30-day trial period with Pro features. When it ends, no subscription starts by itself and nothing is charged – the free Starter plan remains.",
          "The subscription is cancelled in your App Store / Google Play account settings no later than 24 hours before the end of the period. Gloumi cannot cancel the subscription on your behalf."
        ],
        "bullets": [
          "Any unused part of the trial period is forfeited when a subscription is purchased.",
          "When you change tier or period, Apple or Google decide under their own rules when the change takes effect and what is refunded for the time remaining.",
          "Refund requests are handled by Apple or Google under their own rules.",
          "When a subscription ends, paid features are switched off but your data is kept."
        ]
      },
      {
        "title": "Content and conduct rules",
        "paragraphs": [
          "You keep the copyright to the content you upload (photos, Stories, descriptions), but you grant Gloumi a royalty-free licence to display it in the app."
        ],
        "bullets": [
          "Uploading someone else’s content without permission is prohibited.",
          "Offensive, discriminatory or sexually explicit content is prohibited.",
          "Content depicting or encouraging violence is prohibited.",
          "Harassing, threatening or deliberately stalking another user is prohibited.",
          "Encouraging or helping to carry out illegal activity is prohibited.",
          "Unsolicited advertising, chain letters and pyramid schemes are prohibited.",
          "Publishing another person contact details, address or other personal data without their consent is prohibited - including in a review.",
          "Uploading photos of other people without their consent is prohibited.",
          "If a photograph shows a person under 18, it may only be uploaded with the consent of their parent or guardian.",
          "By uploading content you confirm that you hold all the rights needed for it and that it infringes nobody else rights. If a claim is brought against Gloumi because of content you uploaded, you answer for it.",
          "Gloumi may remove content that breaches these rules without prior warning."
        ]
      },
      {
        "title": "Reviews",
        "paragraphs": [
          "Only a client whose visit to that master actually took place may leave a review. A review must be honest and based on personal experience.",
          "A master may reply to a review publicly. A negative review is not in itself a reason to remove it: Gloumi removes only reviews that break the conduct rules, are untrue, are abusive, or have nothing to do with the service provided.",
          "Writing reviews about yourself or your competitors is prohibited, as is offering a client anything in return for a review or for its removal."
        ]
      },
      {
        "title": "Intellectual property and prohibited use",
        "paragraphs": [
          "The app, its name, logo, design, texts, icons and source code belong to Gloumi or are used under licence. Using the app gives you the right to use it for your own purposes - not the right to copy or rework it."
        ],
        "bullets": [
          "Copying, distributing or publishing the content of the app for commercial purposes without written consent from Gloumi is prohibited.",
          "Automated collection of data (bots, scraping) and the creation of copies or derivative works of the app are prohibited.",
          "Attempting to circumvent security measures, access other people accounts, overload the system or distribute malicious code is prohibited.",
          "Using the Gloumi name or logo in a way that suggests a partnership that does not exist is prohibited."
        ]
      },
      {
        "title": "Referral credit and gift cards",
        "paragraphs": [
          "When you invite a new user with your code, you both receive credit; the amount is shown on the invitation screen. The credit is granted only once the invited person has actually completed a first visit - signing up alone is not enough.",
          "A gift card can be bought for between 40 and 1000 euros. Once redeemed, it becomes the same kind of credit on the account."
        ],
        "bullets": [
          "Credit can only be used when paying in the app. It is not exchangeable for cash and cannot be transferred to another person.",
          "Credit has no expiry date and does not disappear on its own.",
          "One person, one account, one code. Creating extra accounts to earn credit is prohibited.",
          "If we suspect credit was obtained by deception (fake accounts, arrangements between users, mass distribution of a code), we may cancel it and restrict the account.",
          "We may change the terms of the programme or the amount of credit, or end the programme; credit already granted remains valid.",
          "An unused gift card may be cancelled within 14 days of purchase. Once it has been used, even in part, it is not refundable."
        ]
      },
      {
        "title": "Prices and pricing errors",
        "paragraphs": [
          "Service prices are set by the master and may change. The price that applies to you is the one shown when the booking was confirmed.",
          "If an obvious error made the displayed price plainly wrong (for example 1 EUR instead of 100 EUR), the booking does not take effect automatically: we tell you, offer you the correct price to confirm, or refund any deposit paid in full."
        ]
      },
      {
        "title": "Reporting illegal content and appealing our decisions",
        "paragraphs": [
          "Gloumi is an intermediary service under the EU Digital Services Act (Regulation 2022/2065). The point of contact for users and authorities is info@gloumi.lt; we correspond in Lithuanian and English.",
          "You can report illegal content at that address or through the report button in the app. Say where the content is and why you believe it is unlawful. We review every report and tell the reporter what we decided.",
          "We handle reports without delay - usually within a few working days - and remove plainly harmful content immediately. A report can be made within 6 months of noticing the content.",
          "When we remove content or restrict an account, we give the reason and the rule we relied on. A user who disagrees may appeal within 6 months by writing to info@gloumi.lt; the appeal is handled by a person, not an automated system, and we tell you the outcome.",
          "If the outcome still does not satisfy you, you may turn to an out-of-court dispute settlement body or to a court. The right to go to court always remains."
        ]
      },
      {
        "title": "Ranking of results",
        "paragraphs": [
          "So that it is clear why one master appears before another, the main parameters are set out below. We hold to the same parameters towards masters - they apply to everyone equally."
        ],
        "bullets": [
          "Search results are determined by the filters you choose yourself: category, city, distance, price range, rating and free slots. Results are not personalised to your past behaviour.",
          "The feed is made of posts from the last 21 days, and their order comes from several things together. The heaviest is how others responded to a post over the last 7 days: tapping through to book, saving, sharing, commenting, dwelling on it and liking it. The master's rating is added (counted from three reviews upwards), the share of cancelled visits is subtracted, and a master with free slots sits a little higher. All of it fades with time: a post's weight halves in roughly 36 hours, so a fresh post rises without needing much attention.",
          "So that you see different masters in the feed, at most four of one master's newest posts are shown, and from the third onwards each one counts for less. Posts you have already seen are moved down.",
          "The feed IS personalised, and it is based on your own actions and settings: posts from masters you follow appear higher; if you are interested in a category, posts from it appear higher too; and if you allowed location, posts from masters closer to you (up to 15 km) are lifted - without a location, distance is counted from the centre of Vilnius. The \"Following\" tab shows the same feed with only the masters you follow left in; it does not order them differently.",
          "A place in the results cannot be bought. Gloumi does not sell advertising and does not move a master up the list for a fee; a subscription unlocks features, not position.",
          "The review average is shown as it is; we do not adjust it and we do not hide the lower ones."
        ]
      },
      {
        "title": "The master is a trader",
        "paragraphs": [
          "A master offering services through Gloumi acts as a trader in their own name. That means that when you enter into a booking you have the full rights of a consumer under Lithuanian law, and you exercise them against the master, not against Gloumi.",
          "If a service were ever offered by someone who is not a trader, that would be stated separately on their profile - in which case consumer protection rules would not apply to you.",
          "Gloumi is not a party to the booking contract, but is answerable for what is on its side: the app, the payments made through it, and for the information on a master profile being what that master themselves provided."
        ]
      },
      {
        "title": "How we verify reviews",
        "paragraphs": [
          "Every review shown is verified, and that is not a promise but how the database works. A review can only be written by the user whose visit to that master is marked as completed; without such a record the database simply refuses the review. So there are no reviews here from people who were never there.",
          "Reviews can be left only after the visit and within a set window. We do not buy, commission or reward reviews, and we do not allow masters to do so either."
        ]
      },
      {
        "title": "For masters: changes, restrictions and complaints",
        "paragraphs": [
          "A master uses Gloumi as a business user, so EU Regulation 2019/1150 on transparency of intermediation services applies to them in addition. Here is what follows from it."
        ],
        "bullets": [
          "We give a master at least 15 days notice of changes to these terms. If you do not agree, you may stop using the service within that time with no consequences.",
          "Before restricting or suspending a master account we state the reasons in writing and give an opportunity to explain the circumstances. Where we end the service entirely we give 30 days notice, except where the law does not allow it or where a breach is repeated or causes immediate harm.",
          "The data a master builds up while using Gloumi - client list, visit history, revenue - belongs to them and is available in the app. After an account ends it is provided on request.",
          "A master sends a complaint about our decision to info@gloumi.lt. Gloumi is a small enterprise, so Articles 11 and 12 of the Regulation (internal complaint system and mediators) do not apply to us - but we do handle complaints, answer in writing and give our grounds.",
          "Gloumi does not provide beauty services and does not compete with masters. We do not list services of our own and we give no master more favourable treatment."
        ]
      },
      {
        "title": "Account restriction and termination",
        "paragraphs": [
          "Gloumi may temporarily restrict or delete an account if these terms are breached or if the activity harms other users.",
          "You can delete your account at any time in the app settings. When an account is deleted, upcoming bookings are cancelled."
        ]
      },
      {
        "title": "Limitation of liability",
        "paragraphs": [
          "The app is provided \"as is\". Gloumi gives no warranty of uninterrupted operation or of being free of errors.",
          "Gloumi’s liability is limited to the extent permitted by the law of the Republic of Lithuania. These provisions do not limit your statutory rights as a consumer."
        ]
      },
      {
        "title": "Complaints and dispute resolution",
        "paragraphs": [
          "If something has gone wrong, write to us first - through Help in the app or at info@gloumi.lt. We confirm receipt within 2 working days and aim to answer on the substance within 14 calendar days.",
          "Disputes about the quality of the service itself are between the client and the master: Gloumi does not provide the service. We help by gathering the facts (the booking record, the messages, the payment data) and we decide what is ours to decide - payments made through the app, deposits, and account actions.",
          "If no agreement is reached, a consumer may apply to the State Consumer Rights Protection Authority (vvtat.lt), which handles such matters out of court and free of charge. The right to go to court always remains."
        ]
      },
      {
        "title": "Changes to the terms and applicable law",
        "paragraphs": [
          "We will announce material changes to these terms in the app or by email at least 14 days before they take effect. By continuing to use Gloumi after the changes take effect, you accept them; if you do not accept them you may delete your account, and that costs you nothing.",
          "We send notices to the email address on your account or show them in the app. You write to us at info@gloumi.lt.",
          "If any provision of these terms is held invalid, the rest remain in force, and we will replace the invalid one with the closest lawful provision.",
          "Gloumi may transfer its rights and obligations under these terms to another legal entity (for example, in a reorganisation). Your rights are not reduced by this, and we will give notice in advance.",
          "The agreement is governed by the law of the Republic of Lithuania. Nothing here deprives you of the rights given to a consumer by the mandatory rules of their country of residence. Disputes are resolved through negotiation and, failing that, in the courts of the Republic of Lithuania."
        ]
      }
    ],
    "privacy": [
      {
        "title": "Who processes your data",
        "paragraphs": [
          "Your personal data is processed by Gloumi as the data controller. Data is processed in accordance with the General Data Protection Regulation (GDPR).",
          "There is one exception, and it matters. What a master writes down ABOUT YOU in their private notes, they collect for their own purposes: there the data controller is the master, and Gloumi only stores those records on their instructions. Address such notes to the master; if they do not reply, write to us and we will help you reach them.",
          "Gloumi has not appointed a data protection officer and is not required to under Art. 37 GDPR. For any data question write to info@gloumi.lt - we answer within one month, and in more complex cases may extend that by a further two months, telling you so."
        ]
      },
      {
        "title": "What data we collect",
        "paragraphs": [
          "We only collect the data needed for the app to work:"
        ],
        "bullets": [
          "Account data: name, username, email address, phone number (optional), date of birth, gender (optional), profile photo.",
          "Master data: service list, prices, working hours, city, portfolio photos.",
          "Booking data: the chosen service, date, time, status and deposit information.",
          "Content: Stories, posts, reviews and chat messages.",
          "Location data: approximate or precise location – only if you grant permission. It is used to find nearby masters and to order the feed (posts from masters closer to you appear higher). Your last known location is stored with your account and is never shown to other users.",
          "Technical data: device type, OS version, push notification token, crash reports."
        ]
      },
      {
        "title": "Why and on what legal basis",
        "paragraphs": [
          "We process data for the following purposes and legal bases:"
        ],
        "bullets": [
          "Performance of a contract – account administration, bookings, payments.",
          "Consent – location, notifications, marketing messages. You can withdraw consent at any time.",
          "Legitimate interest – security, fraud prevention, improving the service.",
          "Legal obligation – accounting and tax requirements.",
          "Date of birth is processed only to check the age limit (see 'Children's privacy'). Other users cannot see it.",
          "Gender (optional) is processed with your consent: a master's job title follows it, and content recommendations may be tailored to you. A client's gender is never shown to other users. Choosing 'Rather not say' deletes the gender you gave."
        ]
      },
      {
        "title": "Is providing data mandatory",
        "paragraphs": [
          "Some data is necessary to perform the contract, and without it the service simply would not work. An email address is needed for the account and for booking notifications; a name so that the master knows who to expect; a date of birth to check the age limit. Without these we cannot create an account.",
          "Everything else is your choice, and declining costs you only that one feature: without a phone number the master cannot call you, without location we cannot show the nearest masters (and distance in the feed is counted from the centre of Vilnius), without notification permission you will not get a reminder about your visit.",
          "We process data following the GDPR principles: only for clearly stated purposes, only as much as those purposes need, no longer than needed, and in a way that keeps it accurate and secure."
        ]
      },
      {
        "title": "Where we get data that you do not give us yourself",
        "paragraphs": [
          "You provide most of the data yourself. But some of it arrives another way, and you should know about that:"
        ],
        "bullets": [
          "From a master - when they book you in themselves or write a private note about you.",
          "From another user - when they tag you in a post or Story, or leave a review about you as a client.",
          "From Apple or Google - signing in with their account gives us your name and email address (with Apple, a private relay address if you choose that).",
          "From Stripe - payment status, refunds and the result of a master identity check. We never receive the card number.",
          "From the device itself - technical data and crash reports when the app fails."
        ]
      },
      {
        "title": "Who we share data with",
        "paragraphs": [
          "We do not sell your data. It is shared only with service providers that help us operate:"
        ],
        "bullets": [
          "Supabase – account authentication and the database.",
          "Cloudflare R2 – storage of photos, videos and voice messages.",
          "Stripe – payment processing, payouts to masters and master identity verification (KYC).",
          "Expo – delivery of push notifications to your device.",
          "Apple / Google – signing in with an Apple or Google account, and subscription processing.",
          "Sentry – collection of error reports so we can fix app failures. Data is stored in the EU.",
          "RevenueCat – verification and status of a master subscription. Receives your account identifier and purchase data from the App Store or Google Play; neither they nor we receive your payment card details.",
          "The master you book with can see your name, photo, contact details and visit history."
        ]
      },
      {
        "title": "Transfers outside the European Economic Area",
        "paragraphs": [
          "Some of the providers listed above are located outside the EEA, or keep infrastructure there, mainly in the United States. That means part of the data is accessible or stored there.",
          "Such transfers are made on the basis of the Standard Contractual Clauses approved by the European Commission and, where applicable, the EU-US Data Privacy Framework. We have data processing agreements with these providers binding them to process data only on our instructions.",
          "Sentry error reports are stored in the EU. Photos and videos in Cloudflare R2 are stored in the EU region.",
          "A copy of the Standard Contractual Clauses is available on request at info@gloumi.lt."
        ]
      },
      {
        "title": "Automated decisions and profiling",
        "paragraphs": [
          "Gloumi does not make automated decisions that produce legal effects concerning you or similarly significantly affect you (Art. 22 GDPR). No account is blocked and no payment refused by an algorithm alone - a person is always answerable for such a decision.",
          "The order things are shown in is not a decision about you, but it should be clear as well - the parameters that determine it are set out in the terms of use under Ranking of results.",
          "We do not build advertising profiles and we do not pass data to advertising networks."
        ]
      },
      {
        "title": "A master’s private notes",
        "paragraphs": [
          "A master can write private notes about a client (for example colour formulas or preferences). These notes are visible only to the master who wrote them. The app does not ask for health data and has no field for it. The master is responsible for not keeping excessive or sensitive data in these notes, health data included, without your consent."
        ]
      },
      {
        "title": "How long we keep data",
        "bullets": [
          "Account data – while the account is active, and for 30 days after deletion.",
          "Booking and payment records – up to 10 years (accounting requirements).",
          "Chat messages – while the account is active or until you delete them.",
          "Stories – automatically stop being shown after 24 hours."
        ],
        "paragraphs": []
      },
      {
        "title": "Your rights",
        "paragraphs": [
          "Under the GDPR you have the right to:"
        ],
        "bullets": [
          "access your data and receive a copy of it;",
          "request correction of inaccurate data;",
          "request erasure of your data (the \"right to be forgotten\");",
          "restrict or object to processing;",
          "transfer your data to another service provider;",
          "withdraw a consent you have given;",
          "lodge a complaint with the State Data Protection Inspectorate (vdai.lrv.lt)."
        ]
      },
      {
        "title": "Data security",
        "paragraphs": [
          "Data is transmitted over an encrypted connection (TLS). Account and booking data is stored in the Supabase infrastructure with row-level access rules, and photos and other files in Cloudflare R2 storage. Passwords are stored only as encrypted hashes – we cannot see them.",
          "No system is completely secure, so we recommend using a unique password."
        ]
      },
      {
        "title": "Children's privacy",
        "paragraphs": [
          "Gloumi is not intended for people under 14. Fourteen is the age Lithuania has set for a child to consent to information society services on their own (GDPR Art. 8(1)). We ask for a date of birth at sign-up and do not create accounts for anyone younger. If we learn that data of a person of that age has been collected anyway, we will delete it without delay."
        ]
      },
      {
        "title": "Cookies and local storage",
        "paragraphs": [
          "Gloumi is an app rather than a website, so it uses no ordinary browser cookies. Some data is still kept on the device itself, and you should know about it just the same."
        ],
        "bullets": [
          "Sign-in session: kept in the device keystore (iOS Keychain, Android Keystore) and encrypted by the operating system. It exists so you do not have to sign in every time you open the app.",
          "Content cache: the most recent feed, Stories and images are kept on the device so the app opens quickly and works on a poor connection. It is cleared when you sign out.",
          "Preferences: language, theme choice and similar settings.",
          "None of this is used for tracking or advertising, and none of it is shared with third parties. Deleting the app deletes it too."
        ]
      },
      {
        "title": "Marketing messages",
        "paragraphs": [
          "We send news and offers only with your consent. You may withdraw that consent at any time - in the notification settings in the app, or through the unsubscribe link in the email; nothing else about your account changes.",
          "Separately from marketing we send service messages - about a booking, a change to it, a payment or security. These cannot be turned off, because without them the service would not work."
        ]
      },
      {
        "title": "Personal data breaches",
        "paragraphs": [
          "If a personal data breach occurred, we would report it to the State Data Protection Inspectorate within 72 hours of becoming aware of it. If the breach were likely to pose a high risk to your rights, we would tell you personally as well - plainly and without delay, saying what is worth doing on your side."
        ]
      },
      {
        "title": "Cancellation and refunds",
        "paragraphs": [
          "The exact cancellation terms are set by each master and shown on their profile. Below is the general rule that applies when a master states nothing else."
        ],
        "bullets": [
          "Cancel more than 24 hours before the appointment and the deposit is refunded in full.",
          "Cancel later than that, or do not turn up, and the deposit is not refunded - it covers the time the master reserved and can no longer sell.",
          "If the master cancels, the deposit is refunded in full regardless of timing.",
          "Refunds go back the way the payment came. We start the refund without delay; how long it takes to reach your account is up to your bank or card issuer.",
          "The remaining balance for the service is paid at the salon. It is never charged through the app, and questions about it are settled with the master.",
          "Gloumi does not provide beauty services and does not arbitrate disputes about their quality; our responsibility is limited to the payment made through the app."
        ]
      }
    ]
  }
};
