/**
 * Terms of Service and Privacy Policy – GENERATED by scripts/gen-from-app.mjs.
 *
 * Source of truth: gloumi-app/src/constants/legal.js in the Gloumi app
 * repository (version 1.1, 2026-09-02). The app shows this same text in
 * its LegalModal and App Store Connect points at the public copy, so the two
 * must never drift: change legal.js, then regenerate this file.
 *
 * The English text is a translation of the Lithuanian original; in case of
 * conflict the Lithuanian version prevails (stated in the source).
 */
export type LegalSection = {
  title: string;
  paragraphs?: string[];
  bullets?: string[];
};

export type LegalLang = "lt" | "en";

export const LEGAL_META = {
  "version": "1.1",
  "lastUpdated": "2026-09-02"
} as const;

export const LEGAL_DOCS: Record<LegalLang, { terms: LegalSection[]; privacy: LegalSection[] }> = {
  "lt": {
    "terms": [
      {
        "title": "Bendrosios nuostatos",
        "paragraphs": [
          "Šios naudojimosi taisyklės yra sutartis tarp Jūsų ir Gloumi. Sukurdami paskyrą arba naudodamiesi programėle Jūs patvirtinate, kad taisykles perskaitėte ir su jomis sutinkate.",
          "Naudotis Gloumi gali tik ne jaunesni nei 16 metų asmenys. Jaunesniems nei 18 metų naudotojams gali reikėti tėvų ar globėjų sutikimo."
        ]
      },
      {
        "title": "Gloumi vaidmuo",
        "paragraphs": [
          "Gloumi yra platforma, jungianti grožio paslaugų specialistus (meistrus) ir klientus. Gloumi pati grožio paslaugų neteikia ir nėra paslaugų sutarties tarp meistro ir kliento šalis."
        ],
        "bullets": [
          "Už paslaugos kokybę, saugą ir atitiktį atsako ją teikiantis meistras.",
          "Meistras pats atsako už veiklos registraciją, licencijas, higienos reikalavimus ir mokesčius.",
          "Gloumi neatsako už žalą, kilusią dėl netinkamai suteiktos paslaugos, tačiau tarpininkauja sprendžiant ginčus."
        ]
      },
      {
        "title": "Paskyra ir vaidmenys",
        "paragraphs": [
          "Registruojantis sukuriama kliento paskyra. Meistro funkcijos tampa prieinamos tik atskirai užpildžius ir pateikus meistro profilį.",
          "Jūs atsakote už savo prisijungimo duomenų saugumą ir už visus veiksmus, atliktus iš Jūsų paskyros. Apie neteisėtą prieigą privalote nedelsdami pranešti."
        ],
        "bullets": [
          "Draudžiama kurti paskyrą svetimu vardu ar teikti klaidingus duomenis.",
          "Vienam asmeniui leidžiama turėti vieną paskyrą.",
          "Gloumi gali paprašyti patvirtinti meistro tapatybę ar kvalifikaciją."
        ]
      },
      {
        "title": "Rezervacijos ir avansas",
        "paragraphs": [
          "Rezervacija laikoma sudaryta, kai meistras ją patvirtina programėlėje. Meistras gali nustatyti privalomą avansą – fiksuotą sumą arba procentą nuo paslaugos kainos.",
          "Sumokėtas avansas yra užskaitomas į galutinę paslaugos kainą."
        ],
        "bullets": [
          "Atšaukus vizitą likus daugiau nei 24 val., avansas grąžinamas.",
          "Atšaukus likus mažiau nei 24 val. arba neatvykus, avansas negrąžinamas.",
          "Jei vizitą atšaukia meistras, avansas grąžinamas visas.",
          "Vizito perkėlimo atveju avansas perkeliamas į naują laiką."
        ]
      },
      {
        "title": "Meistro prenumerata (Pro)",
        "paragraphs": [
          "Meistro funkcijos siūlomos kaip mėnesinė prenumerata su nemokamu bandomuoju laikotarpiu. Prenumerata perkama per Apple App Store arba Google Play ir automatiškai atsinaujina, kol jos neatšaukiate.",
          "Prenumerata atšaukiama Jūsų App Store / Google Play paskyros nustatymuose ne vėliau kaip likus 24 val. iki laikotarpio pabaigos. Gloumi negali atšaukti prenumeratos už Jus."
        ],
        "bullets": [
          "Nepanaudotas bandomojo laikotarpio likutis dingsta įsigijus prenumeratą.",
          "Pinigų grąžinimo klausimus sprendžia Apple arba Google pagal savo taisykles.",
          "Pasibaigus prenumeratai, Pro funkcijos išjungiamos, bet Jūsų duomenys išsaugomi."
        ]
      },
      {
        "title": "Turinys ir elgesio taisyklės",
        "paragraphs": [
          "Jūs išlaikote savo įkelto turinio (nuotraukų, „Stories“, aprašymų) autorių teises, bet suteikiate Gloumi neatlygintiną licenciją jį rodyti programėlėje."
        ],
        "bullets": [
          "Draudžiama kelti svetimą turinį be leidimo.",
          "Draudžiamas įžeidžiantis, diskriminuojantis ar erotinio pobūdžio turinys.",
          "Draudžiama kelti kitų asmenų nuotraukas be jų sutikimo.",
          "Atsiliepimai turi būti sąžiningi ir pagrįsti realiu vizitu.",
          "Gloumi gali pašalinti taisyklių neatitinkantį turinį be išankstinio įspėjimo."
        ]
      },
      {
        "title": "Paskyros ribojimas ir nutraukimas",
        "paragraphs": [
          "Gloumi gali laikinai apriboti arba panaikinti paskyrą, jei pažeidžiamos šios taisyklės arba veikla kelia žalą kitiems naudotojams.",
          "Jūs galite bet kada ištrinti savo paskyrą programėlės nustatymuose. Ištrynus paskyrą, būsimos rezervacijos atšaukiamos."
        ]
      },
      {
        "title": "Atsakomybės ribojimas",
        "paragraphs": [
          "Programėlė teikiama „tokia, kokia yra“. Gloumi nesuteikia garantijų dėl nepertraukiamo veikimo ar klaidų nebuvimo.",
          "Gloumi atsakomybė ribojama tiek, kiek tai leidžia Lietuvos Respublikos teisė. Šios nuostatos neriboja Jūsų kaip vartotojo teisių pagal imperatyvias teisės normas."
        ]
      },
      {
        "title": "Taisyklių keitimas ir taikoma teisė",
        "paragraphs": [
          "Apie esminius taisyklių pakeitimus pranešime programėlėje arba el. paštu. Toliau naudodamiesi Gloumi po pakeitimų įsigaliojimo, Jūs su jais sutinkate.",
          "Sutarčiai taikoma Lietuvos Respublikos teisė. Ginčai sprendžiami derybomis, o nepavykus – Lietuvos Respublikos teismuose. Vartotojai taip pat gali kreiptis į Valstybinę vartotojų teisių apsaugos tarnybą."
        ]
      }
    ],
    "privacy": [
      {
        "title": "Kas tvarko Jūsų duomenis",
        "paragraphs": [
          "Jūsų asmens duomenis tvarko Gloumi kaip duomenų valdytojas. Duomenys tvarkomi pagal Bendrąjį duomenų apsaugos reglamentą (BDAR / GDPR)."
        ]
      },
      {
        "title": "Kokius duomenis renkame",
        "paragraphs": [
          "Renkame tik tuos duomenis, kurie reikalingi programėlės veikimui:"
        ],
        "bullets": [
          "Paskyros duomenys: vardas, naudotojo vardas, el. paštas, telefono numeris (neprivalomas), gimimo data, profilio nuotrauka.",
          "Meistro duomenys: paslaugų sąrašas, kainos, darbo laikas, miestas, portfolio nuotraukos.",
          "Rezervacijų duomenys: pasirinkta paslauga, data, laikas, statusas, avanso informacija.",
          "Turinys: „Stories“, įrašai, atsiliepimai, susirašinėjimo žinutės.",
          "Vietos duomenys: apytikslė arba tiksli buvimo vieta – tik jei suteikiate leidimą ir tik artimiausių meistrų paieškai.",
          "Techniniai duomenys: įrenginio tipas, OS versija, pranešimų žetonas (push token), klaidų ataskaitos."
        ]
      },
      {
        "title": "Kodėl ir kokiu pagrindu",
        "paragraphs": [
          "Duomenis tvarkome šiais tikslais ir teisiniais pagrindais:"
        ],
        "bullets": [
          "Sutarties vykdymas – paskyros administravimas, rezervacijos, mokėjimai.",
          "Sutikimas – vietos nustatymas, pranešimai, rinkodaros žinutės. Sutikimą galite bet kada atšaukti.",
          "Teisėtas interesas – saugumas, sukčiavimo prevencija, paslaugos tobulinimas.",
          "Teisinė prievolė – apskaitos ir mokestiniai reikalavimai.",
          "Gimimo data tvarkoma tik amžiaus ribai patikrinti (žr. „Vaikų privatumas“). Kitiems naudotojams ji nematoma."
        ]
      },
      {
        "title": "Kam perduodame duomenis",
        "paragraphs": [
          "Duomenų neparduodame. Jie perduodami tik paslaugų teikėjams, kurie padeda mums veikti:"
        ],
        "bullets": [
          "Supabase – paskyrų autentifikacija ir duomenų bazė.",
          "Cloudflare R2 – nuotraukų, vaizdo įrašų ir balso žinučių saugojimas.",
          "Stripe – mokėjimų vykdymas, išmokos meistrams ir meistro tapatybės patikra (KYC).",
          "Expo – push pranešimų pristatymas į įrenginį.",
          "Apple / Google – prisijungimas per Apple ar Google paskyrą ir prenumeratų apdorojimas.",
          "Sentry – klaidų ataskaitų surinkimas, kad galėtume pataisyti programėlės gedimus. Duomenys saugomi ES.",
          "Meistrui, pas kurį registruojatės, matomas Jūsų vardas, nuotrauka, kontaktai ir vizitų istorija."
        ]
      },
      {
        "title": "Meistro privatūs užrašai",
        "paragraphs": [
          "Meistras gali kurti privačias pastabas apie klientą (pvz., dažų formules ar pageidavimus). Šios pastabos matomos tik jas sukūrusiam meistrui. Programėlė neprašo sveikatos duomenų ir neturi jiems skirto lauko. Meistras atsako už tai, kad pastabose nebūtų perteklinių ar jautrių duomenų, įskaitant sveikatos, be Jūsų sutikimo."
        ]
      },
      {
        "title": "Kiek laiko saugome",
        "bullets": [
          "Paskyros duomenys – kol paskyra aktyvi, ir 30 dienų po ištrynimo.",
          "Rezervacijų ir mokėjimų įrašai – iki 10 metų (apskaitos reikalavimai).",
          "Susirašinėjimo žinutės – kol paskyra aktyvi arba kol jas ištrinate.",
          "„Stories“ – automatiškai nustoja būti rodomos po 24 valandų."
        ],
        "paragraphs": []
      },
      {
        "title": "Jūsų teisės",
        "paragraphs": [
          "Pagal BDAR turite teisę:"
        ],
        "bullets": [
          "susipažinti su savo duomenimis ir gauti jų kopiją;",
          "reikalauti ištaisyti netikslius duomenis;",
          "reikalauti ištrinti duomenis („teisė būti pamirštam“);",
          "apriboti tvarkymą arba jam nesutikti;",
          "perkelti duomenis kitam paslaugų teikėjui;",
          "atšaukti duotą sutikimą;",
          "pateikti skundą Valstybinei duomenų apsaugos inspekcijai (vdai.lrv.lt)."
        ]
      },
      {
        "title": "Duomenų sauga",
        "paragraphs": [
          "Duomenys perduodami šifruotu ryšiu (TLS). Paskyrų ir rezervacijų duomenys saugomi Supabase infrastruktūroje su eilučių lygio prieigos taisyklėmis, o nuotraukos ir kiti failai – Cloudflare R2 saugykloje. Slaptažodžiai saugomi tik šifruotos santraukos pavidalu – jų nematome.",
          "Nė viena sistema nėra visiškai saugi, todėl rekomenduojame naudoti unikalų slaptažodį."
        ]
      },
      {
        "title": "Vaikų privatumas",
        "paragraphs": [
          "Gloumi neskirta jaunesniems nei 14 metų asmenims. 14 metų yra Lietuvoje nustatyta riba, nuo kurios vaikas gali pats duoti sutikimą dėl informacinės visuomenės paslaugų (BDAR 8 str. 1 d.). Registruojantis prašome nurodyti gimimo datą ir jaunesnių paskyrų nekuriame. Sužinoję, kad tokio amžiaus asmens duomenys vis dėlto buvo surinkti, juos nedelsdami ištrinsime."
        ]
      },
      {
        "title": "Slapukai ir vietinė saugykla",
        "paragraphs": [
          "Gloumi yra programėlė, o ne svetainė, todėl įprastų naršyklės slapukų ji nenaudoja. Tačiau dalis duomenų saugoma pačiame įrenginyje, ir apie tai turite žinoti tiek pat."
        ],
        "bullets": [
          "Prisijungimo sesija: saugoma įrenginio saugykloje (iOS Keychain, Android Keystore), šifruota operacinės sistemos priemonėmis. Reikalinga tam, kad nereikėtų prisijungti iš naujo kaskart atidarius programėlę.",
          "Turinio talpykla: paskutinis srautas, „Stories\" ir paveikslėliai laikomi įrenginyje, kad programėlė atsidarytų greitai ir veiktų prastame ryšyje. Atsijungus ji išvaloma.",
          "Nustatymai: kalba, temos pasirinkimas ir panašūs pasirinkimai.",
          "Nė vienas iš šių įrašų nėra naudojamas sekimui ar reklamai, ir jie nėra perduodami tretiesiems asmenims. Ištrynus programėlę, ištrinami ir jie."
        ]
      },
      {
        "title": "Atšaukimas ir pinigų grąžinimas",
        "paragraphs": [
          "Konkrečias atšaukimo sąlygas nustato pats meistras ir jos rodomos prie jo anketos. Žemiau – bendra tvarka, galiojanti, kai meistras nenurodo kitaip."
        ],
        "bullets": [
          "Atšaukus likus daugiau nei 24 val. iki vizito, sumokėtas avansas grąžinamas visas.",
          "Atšaukus vėliau nei prieš 24 val. arba neatvykus, avansas negrąžinamas – jis dengia meistro rezervuotą ir nebeparduodamą laiką.",
          "Meistrui atšaukus vizitą, avansas grąžinamas visas, nepriklausomai nuo laiko.",
          "Pinigai grąžinami tuo pačiu būdu, kuriuo buvo sumokėti. Grąžinimą inicijuojame nedelsdami; kiek užtruks lėšos jūsų sąskaitoje, priklauso nuo banko ar kortelės išdavėjo.",
          "Likusią sumos dalį už paslaugą mokate salone – ji per programėlę nenuskaitoma ir jos grąžinimo klausimai sprendžiami su meistru.",
          "Gloumi neteikia grožio paslaugų ir nesprendžia ginčų dėl jų kokybės; mūsų atsakomybė apsiriboja per programėlę atliktu mokėjimu."
        ]
      }
    ]
  },
  "en": {
    "terms": [
      {
        "title": "General provisions",
        "paragraphs": [
          "These terms of use form an agreement between you and Gloumi. By creating an account or using the app you confirm that you have read and accepted these terms.",
          "Gloumi may only be used by people aged 16 or over. Users under 18 may need the consent of a parent or guardian."
        ]
      },
      {
        "title": "The role of Gloumi",
        "paragraphs": [
          "Gloumi is a platform that connects beauty professionals (masters) with clients. Gloumi does not provide beauty services itself and is not a party to the service contract between the master and the client."
        ],
        "bullets": [
          "The master providing the service is responsible for its quality, safety and compliance.",
          "The master is responsible for their own business registration, licences, hygiene requirements and taxes.",
          "Gloumi is not liable for damage caused by an improperly provided service, but will mediate in resolving disputes."
        ]
      },
      {
        "title": "Account and roles",
        "paragraphs": [
          "Registration creates a client account. Master features become available only after a master profile is separately filled in and submitted.",
          "You are responsible for keeping your login details secure and for all activity carried out from your account. You must report unauthorised access without delay."
        ],
        "bullets": [
          "Creating an account under someone else’s name or providing false data is prohibited.",
          "One person may hold one account.",
          "Gloumi may ask a master to confirm their identity or qualifications."
        ]
      },
      {
        "title": "Bookings and deposits",
        "paragraphs": [
          "A booking is considered made once the master confirms it in the app. A master may require a deposit – either a fixed amount or a percentage of the service price.",
          "A paid deposit is credited towards the final price of the service."
        ],
        "bullets": [
          "If a visit is cancelled more than 24 hours in advance, the deposit is refunded.",
          "If it is cancelled less than 24 hours in advance, or in case of a no-show, the deposit is not refunded.",
          "If the master cancels the visit, the deposit is refunded in full.",
          "If a visit is rescheduled, the deposit is carried over to the new time."
        ]
      },
      {
        "title": "Master subscription (Pro)",
        "paragraphs": [
          "Master features are offered as a monthly subscription with a free trial period. The subscription is purchased through the Apple App Store or Google Play and renews automatically until you cancel it.",
          "The subscription is cancelled in your App Store / Google Play account settings no later than 24 hours before the end of the period. Gloumi cannot cancel the subscription on your behalf."
        ],
        "bullets": [
          "Any unused part of the trial period is forfeited when a subscription is purchased.",
          "Refund requests are handled by Apple or Google under their own rules.",
          "When a subscription ends, Pro features are switched off but your data is kept."
        ]
      },
      {
        "title": "Content and conduct rules",
        "paragraphs": [
          "You keep the copyright to the content you upload (photos, Stories, descriptions), but you grant Gloumi a royalty-free licence to display it in the app."
        ],
        "bullets": [
          "Uploading someone else’s content without permission is prohibited.",
          "Offensive, discriminatory or sexually explicit content is prohibited.",
          "Uploading photos of other people without their consent is prohibited.",
          "Reviews must be honest and based on a real visit.",
          "Gloumi may remove content that breaches these rules without prior warning."
        ]
      },
      {
        "title": "Account restriction and termination",
        "paragraphs": [
          "Gloumi may temporarily restrict or delete an account if these terms are breached or if the activity harms other users.",
          "You can delete your account at any time in the app settings. When an account is deleted, upcoming bookings are cancelled."
        ]
      },
      {
        "title": "Limitation of liability",
        "paragraphs": [
          "The app is provided \"as is\". Gloumi gives no warranty of uninterrupted operation or of being free of errors.",
          "Gloumi’s liability is limited to the extent permitted by the law of the Republic of Lithuania. These provisions do not limit your statutory rights as a consumer."
        ]
      },
      {
        "title": "Changes to the terms and applicable law",
        "paragraphs": [
          "We will announce material changes to these terms in the app or by email. By continuing to use Gloumi after the changes take effect, you accept them.",
          "The agreement is governed by the law of the Republic of Lithuania. Disputes are resolved through negotiation and, failing that, in the courts of the Republic of Lithuania. Consumers may also contact the State Consumer Rights Protection Authority."
        ]
      }
    ],
    "privacy": [
      {
        "title": "Who processes your data",
        "paragraphs": [
          "Your personal data is processed by Gloumi as the data controller. The data is processed in accordance with the General Data Protection Regulation (GDPR)."
        ]
      },
      {
        "title": "What data we collect",
        "paragraphs": [
          "We only collect the data needed for the app to work:"
        ],
        "bullets": [
          "Account data: name, username, email address, phone number (optional), date of birth, profile photo.",
          "Master data: service list, prices, working hours, city, portfolio photos.",
          "Booking data: the chosen service, date, time, status and deposit information.",
          "Content: Stories, posts, reviews and chat messages.",
          "Location data: approximate or precise location – only if you grant permission, and only to find nearby masters.",
          "Technical data: device type, OS version, push notification token, crash reports."
        ]
      },
      {
        "title": "Why and on what legal basis",
        "paragraphs": [
          "We process data for the following purposes and legal bases:"
        ],
        "bullets": [
          "Performance of a contract – account administration, bookings, payments.",
          "Consent – location, notifications, marketing messages. You can withdraw consent at any time.",
          "Legitimate interest – security, fraud prevention, improving the service.",
          "Legal obligation – accounting and tax requirements.",
          "Date of birth is processed only to check the age limit (see 'Children's privacy'). Other users cannot see it."
        ]
      },
      {
        "title": "Who we share data with",
        "paragraphs": [
          "We do not sell your data. It is shared only with service providers that help us operate:"
        ],
        "bullets": [
          "Supabase – account authentication and the database.",
          "Cloudflare R2 – storage of photos, videos and voice messages.",
          "Stripe – payment processing, payouts to masters and master identity verification (KYC).",
          "Expo – delivery of push notifications to your device.",
          "Apple / Google – signing in with an Apple or Google account, and subscription processing.",
          "Sentry – collection of error reports so we can fix app failures. Data is stored in the EU.",
          "The master you book with can see your name, photo, contact details and visit history."
        ]
      },
      {
        "title": "A master’s private notes",
        "paragraphs": [
          "A master can write private notes about a client (for example colour formulas or preferences). These notes are visible only to the master who wrote them. The app does not ask for health data and has no field for it. The master is responsible for not keeping excessive or sensitive data in these notes, health data included, without your consent."
        ]
      },
      {
        "title": "How long we keep data",
        "bullets": [
          "Account data – while the account is active, and for 30 days after deletion.",
          "Booking and payment records – up to 10 years (accounting requirements).",
          "Chat messages – while the account is active or until you delete them.",
          "Stories – automatically stop being shown after 24 hours."
        ],
        "paragraphs": []
      },
      {
        "title": "Your rights",
        "paragraphs": [
          "Under the GDPR you have the right to:"
        ],
        "bullets": [
          "access your data and receive a copy of it;",
          "request correction of inaccurate data;",
          "request erasure of your data (the \"right to be forgotten\");",
          "restrict or object to processing;",
          "transfer your data to another service provider;",
          "withdraw a consent you have given;",
          "lodge a complaint with the State Data Protection Inspectorate (vdai.lrv.lt)."
        ]
      },
      {
        "title": "Data security",
        "paragraphs": [
          "Data is transmitted over an encrypted connection (TLS). Account and booking data is stored in the Supabase infrastructure with row-level access rules, and photos and other files in Cloudflare R2 storage. Passwords are stored only as encrypted hashes – we cannot see them.",
          "No system is completely secure, so we recommend using a unique password."
        ]
      },
      {
        "title": "Children's privacy",
        "paragraphs": [
          "Gloumi is not intended for people under 14. Fourteen is the age Lithuania has set for a child to consent to information society services on their own (GDPR Art. 8(1)). We ask for a date of birth at sign-up and do not create accounts for anyone younger. If we learn that data of a person of that age has been collected anyway, we will delete it without delay."
        ]
      },
      {
        "title": "Cookies and local storage",
        "paragraphs": [
          "Gloumi is an app rather than a website, so it uses no ordinary browser cookies. Some data is still kept on the device itself, and you should know about it just the same."
        ],
        "bullets": [
          "Sign-in session: kept in the device keystore (iOS Keychain, Android Keystore) and encrypted by the operating system. It exists so you do not have to sign in every time you open the app.",
          "Content cache: the most recent feed, Stories and images are kept on the device so the app opens quickly and works on a poor connection. It is cleared when you sign out.",
          "Preferences: language, theme choice and similar settings.",
          "None of this is used for tracking or advertising, and none of it is shared with third parties. Deleting the app deletes it too."
        ]
      },
      {
        "title": "Cancellation and refunds",
        "paragraphs": [
          "The exact cancellation terms are set by each master and shown on their profile. Below is the general rule that applies when a master states nothing else."
        ],
        "bullets": [
          "Cancel more than 24 hours before the appointment and the deposit is refunded in full.",
          "Cancel later than that, or do not turn up, and the deposit is not refunded - it covers the time the master reserved and can no longer sell.",
          "If the master cancels, the deposit is refunded in full regardless of timing.",
          "Refunds go back the way the payment came. We start the refund without delay; how long it takes to reach your account is up to your bank or card issuer.",
          "The remaining balance for the service is paid at the salon. It is never charged through the app, and questions about it are settled with the master.",
          "Gloumi does not provide beauty services and does not arbitrate disputes about their quality; our responsibility is limited to the payment made through the app."
        ]
      }
    ]
  }
};
